(()=>{'use strict';
const $=id=>document.getElementById(id);if(!$('market-app'))return;
const KEY='mtp.web.listings',FAV='mtp.market.favorites',MAX=100;
const categories={maison:'Maison & déco',multimedia:'Multimédia',mobilite:'Vélos & mobilité',mode:'Mode & accessoires',culture:'Livres & créations',services:'Services & savoir-faire',dons:'Dons & entraide'};
const conditions=['Neuf','Très bon état','Bon état','À réparer','Sans objet'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const illustrations={
 mobilite:'<circle cx="54" cy="113" r="31"/><circle cx="170" cy="113" r="31"/><path d="M54 113l35-62 41 62H54l29-48h65l22 48M132 30h22l-6 35M77 49h28"/>',
 maison:'<path d="M63 23h94l22 67H41zM110 91v49M78 145h64"/><path d="M70 38h35" opacity=".4"/>',
 multimedia:'<rect x="45" y="44" width="130" height="88" rx="12"/><circle cx="110" cy="86" r="28"/><circle cx="110" cy="86" r="17"/><path d="M65 43l12-17h40l13 17M147 60h12"/>',
 mode:'<path d="M62 48h96l14 100H48zM84 50V30a26 26 0 0 1 52 0v20M76 85h68"/>',
 culture:'<path d="M36 34q40-12 74 8v108q-35-20-74-8zM110 42q35-20 74-8v108q-40-12-74 8M53 62l37 3M53 80l37 3M132 65l32-5M132 83l32-5"/>',
 services:'<path d="M80 23a35 35 0 0 0 40 45l53 58a13 13 0 0 1-20 18L99 83a35 35 0 0 1-39-49l17 19 21-4 7-19z"/>',
 dons:'<path d="M110 137S38 95 38 57a32 32 0 0 1 59-17l13 17 13-17a32 32 0 0 1 59 17c0 38-72 80-72 80z"/>'};
const colors={maison:'#ece4d4',multimedia:'#dde3e1',mobilite:'#e4ead9',mode:'#e9dfd5',culture:'#e5e2d6',services:'#dce7df',dons:'#e9e5cf'};
const examples=[
 ['velo','Vélo de ville, seconde vie','mobilite','Très bon état','85','Montpellier','Un exemple pour présenter un vélo : taille du cadre, état des freins, équipements et éventuelles réparations. Cet objet est illustratif et n’est pas proposé à la vente.'],
 ['lampe','Une lumière pour votre salon','maison','Bon état','24','Castelnau-le-Lez','Une annonce de décoration peut préciser les dimensions, les matériaux et l’état de fonctionnement. Cette lampe est un exemple de présentation, pas une offre disponible.'],
 ['livres','Des livres à faire voyager','culture','Bon état','0','Montpellier','Un don peut donner une seconde vie aux livres. Indiquez les titres, l’état et les modalités de remise. Ce lot est un exemple, pas un don réellement disponible.'],
 ['photo','L’envie de photographier','multimedia','Très bon état','120','Lattes','Pour du matériel photo : modèle, accessoires, fonctionnement et défauts éventuels. Cet appareil illustré est un exemple, pas un stock disponible.'],
 ['sac','Le sac qui vous accompagne','mode','Très bon état','18','Montpellier','Un exemple de fiche pour un accessoire de seconde main : matière, dimensions et état. Aucun vendeur ni produit réel n’est associé à cet exemple.'],
 ['reparer','Un coup de main pour réparer','services','Sans objet','','Juvignac','Décrivez le savoir-faire proposé, le périmètre d’intervention et la disponibilité à convenir. Cette fiche illustre une annonce de service ; elle ne constitue pas une prestation disponible.']
].map(([id,title,category,condition,price,location,description],i)=>({id:'example-'+id,title,category,condition,price,currency:'EUR',location,description,free:price==='0',photos:[],example:true,createdAt:Date.UTC(2026,8,25)-i*60000}));
let storageProblem=false,noticeTimer;
function read(key,fallback){try{const s=localStorage.getItem(key);return s===null?fallback:JSON.parse(s)}catch{storageProblem=true;return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
function notify(text){$('market-notice').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('market-notice').textContent='',6500)}
function normalize(v){if(!v||typeof v!=='object'||typeof v.id!=='string'||!v.id||v.id.length>150||v.id.startsWith('example-')||typeof v.title!=='string'||!v.title.trim()||typeof v.description!=='string'||!v.description.trim())return null;
 const category=Object.hasOwn(categories,v.category)?v.category:v.type==='Don'?'dons':['Service','Savoir-faire'].includes(v.type)?'services':'maison';
 const price=v.price==null?'':String(v.price);if(price!==''&&(!Number.isFinite(Number(price))||Number(price)<0||Number(price)>1e12))return null;
 const photos=Array.isArray(v.photos)?v.photos.filter(p=>typeof p==='string'&&p.length<=450000&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(p)).slice(0,4):[];
 return {id:v.id,title:v.title.trim().slice(0,100),description:v.description.trim().slice(0,2000),category,condition:conditions.includes(v.condition)?v.condition:'Bon état',price,currency:v.currency==='EUR'?'EUR':'MTP',location:typeof v.location==='string'?v.location.slice(0,80):'',free:v.free===true||v.type==='Don',photos,createdAt:Number.isFinite(v.createdAt)&&v.createdAt>0?v.createdAt:0,type:category==='dons'?'Don':category==='services'?'Service':'Objet'};
}
function normalizeList(raw){return Array.isArray(raw)?raw.map(normalize).filter(Boolean):[]}
let drafts=normalizeList(read(KEY,[]));const rawFavorites=read(FAV,[]);let favorites=new Set(Array.isArray(rawFavorites)?rawFavorites.filter(x=>typeof x==='string'):[]);
let publicListings=[],catalogBusy=false,lastFetch=0;let view='public',photos=[],photoEpoch=0,processing=false,pendingDelete=null,lastTrigger=null;
const fold=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const priceText=p=>p.free?'À donner':p.price===''?'À convenir':new Intl.NumberFormat('fr-FR',{maximumFractionDigits:8}).format(Number(p.price))+(p.currency==='EUR'?' €':' MTP');
const picture=p=>p.photos.length?`<img src="${esc(p.photos[0])}" alt="${esc(p.title)}" loading="lazy">`:`<svg viewBox="0 0 220 175" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${illustrations[p.category]||illustrations.maison}</svg>`;
function all(){return [...drafts,...publicListings,...examples]}function item(id){return all().find(x=>x.id===id)}
function current(){return view==='public'?publicListings:view==='mine'?drafts:view==='favorites'?all().filter(x=>favorites.has(x.id)):examples}
function setView(next){view=next;render()}
function filters(){return {query:fold($('market-query').value.trim()),location:fold($('market-location').value.trim()),category:$('filter-category').value,condition:$('filter-condition').value,price:$('filter-price').value,currency:$('filter-currency').value,free:$('filter-free').checked}}
function render(){const f=filters();let list=current().filter(p=>(!f.query||fold(p.title+' '+p.description+' '+categories[p.category]).includes(f.query))&&(!f.location||fold(p.location).includes(f.location))&&(f.category==='all'||p.category===f.category)&&(f.condition==='all'||p.condition===f.condition)&&(!f.free||p.free));
 const sort=$('market-sort').value;
 if(f.price!==''||sort==='low'||sort==='high')list=list.filter(p=>p.free||(p.currency===f.currency&&p.price!==''&&(f.price===''||Number(p.price)<=Number(f.price))));
 list.sort(sort==='title'?(a,b)=>a.title.localeCompare(b.title,'fr'):sort==='low'?(a,b)=>(a.free?0:Number(a.price))-(b.free?0:Number(b.price)):sort==='high'?(a,b)=>(b.free?0:Number(b.price))-(a.free?0:Number(a.price)):(a,b)=>b.createdAt-a.createdAt);
 $('favorite-count').textContent=all().filter(p=>favorites.has(p.id)).length;
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
 document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===f.category)));
 $('catalog-title').textContent=view==='mine'?'Vos annonces, à votre image.':view==='favorites'?'Vos coups de cœur.':'Le coin des trouvailles.';
 $('catalog-eyebrow').textContent=view==='mine'?'VOTRE ESPACE · SUR CET APPAREIL':view==='favorites'?'À RETROUVER PLUS TARD':view==='public'?'LES ANNONCES DE LA COMMUNAUTÉ':'EXEMPLES DE PRÉSENTATION';
 $('market-result-count').textContent=list.length+' '+(view==='discover'?'exemple'+(list.length>1?'s':'')+' · non disponible'+(list.length>1?'s':''):view==='mine'?'annonce'+(list.length>1?'s':'')+' locale'+(list.length>1?'s':''):view==='public'?'annonce'+(list.length>1?'s':'')+' publique'+(list.length>1?'s':''):'favori'+(list.length>1?'s':''));
 const summaries=[];if(f.query)summaries.push('Recherche : '+$('market-query').value.trim());if(f.location)summaries.push('Ville : '+$('market-location').value.trim());if(sort==='low'||sort==='high')summaries.push('Prix en '+f.currency+' et dons uniquement ; montants à convenir exclus.');$('market-filter-summary').textContent=summaries.join(' · ');
 $('market-results').innerHTML=list.map(p=>`<article class="product-card"><button class="favorite-button" type="button" data-favorite="${esc(p.id)}" aria-pressed="${favorites.has(p.id)}" aria-label="${favorites.has(p.id)?'Retirer des favoris':'Ajouter aux favoris'} : ${esc(p.title)}">${favorites.has(p.id)?'♥':'♡'}</button><button class="product-open" type="button" data-open="${esc(p.id)}" aria-label="Voir la fiche : ${esc(p.title)}"><div class="product-picture" style="--picture:${colors[p.category]}">${picture(p)}<span class="product-badge">${p.example?'Exemple · non disponible':p.public?'Annonce de la communauté':'Mon annonce · non publiée'}</span></div><div class="product-info"><h3>${esc(p.title)}</h3><span class="product-price">${esc(priceText(p))}</span><span class="product-meta">${esc(p.location||'Lieu à préciser')}</span><span class="product-meta">${esc(categories[p.category])}</span><span class="product-state">${esc(p.condition)}</span></div></button></article>`).join('');
 if(!list.length){const empty=document.createElement('div');empty.className='empty-market';const filtered=f.query||f.location||f.category!=='all'||f.condition!=='all'||f.free||f.price!==''||sort!=='recent';empty.innerHTML=`<span aria-hidden="true">✳</span><h3>${filtered?'Aucune trouvaille avec ces critères.':view==='mine'?'Votre première annonce commence ici.':view==='public'?'Les premières annonces commencent avec vous.':'Gardez vos coups de cœur à portée de main.'}</h3><p>${filtered?'Essayez une autre recherche ou retirez quelques filtres.':view==='mine'?'Ajoutez vos photos, racontez votre objet ou votre savoir-faire. Votre annonce restera sur cet appareil.':view==='public'?'Aucune annonce publique à afficher pour le moment. Préparez la vôtre ou découvrez les exemples de présentation.':'Touchez le cœur d’une fiche pour la retrouver dans cet espace.'}</p><button type="button" class="m-button" ${filtered?'data-reset':view==='mine'?'data-create':'data-view="discover"'}>${filtered?'Effacer les filtres':view==='mine'?'Préparer une annonce':'Explorer les exemples'}</button>`;$('market-results').append(empty)}
}
function reset(){for(const id of ['market-query','market-location','filter-price'])$(id).value='';$('filter-category').value='all';$('filter-condition').value='all';$('filter-free').checked=false;$('market-sort').value='recent';render()}
function openDialog(id){lastTrigger=document.activeElement;$(id).showModal()}function closeDialog(id){$(id).close();if(lastTrigger?.isConnected)lastTrigger.focus()}
function photoPreview(){$('draft-photo-preview').innerHTML=photos.map((src,i)=>`<div class="photo-preview"><img src="${src}" alt="Photo ${i+1} de votre annonce"><button type="button" data-remove-photo="${i}" aria-label="Retirer la photo ${i+1}">×</button></div>`).join('')}
function edit(p=null){photoEpoch++;processing=false;$('market-listing-form').reset();$('draft-save').disabled=false;$('draft-photos').disabled=false;$('edit-id').value=p?.id||'';$('listing-dialog-title').textContent=p?'Modifier mon annonce':'Préparer une annonce';$('draft-title').value=p?.title||'';$('draft-description').value=p?.description||'';$('draft-category').value=p?.category||'maison';$('draft-condition').value=p?.condition||'Bon état';$('draft-price').value=p?.price||'';$('draft-currency').value=p?.currency||'EUR';$('draft-location').value=p?.location||'';$('draft-free').checked=!!p?.free;$('draft-price').disabled=!!p?.free;photos=[...(p?.photos||[])];photoPreview();$('draft-status').textContent='';openDialog('listing-dialog');$('draft-title').focus()}
function detail(p){const isFav=favorites.has(p.id);$('product-detail').innerHTML=`<div class="detail-grid"><div><div class="product-picture" id="detail-picture" style="--picture:${colors[p.category]}">${picture(p)}</div>${p.photos.length>1?'<div class="detail-thumbs">'+p.photos.map((src,i)=>`<button type="button" data-photo-index="${i}" data-item="${esc(p.id)}" aria-label="Voir la photo ${i+1}" aria-pressed="${i===0}"><img src="${src}" alt=""></button>`).join('')+'</div>':''}</div><div class="detail-copy"><span class="product-state">${esc(categories[p.category])}</span><h2 id="product-title">${esc(p.title)}</h2><span class="product-price">${esc(priceText(p))}</span><p>${esc(p.location||'Lieu à préciser')} · ${esc(p.condition)}</p><p>${esc(p.description)}</p><div class="detail-status">${p.example?'Exemple de présentation. Cette fiche, son illustration et son prix ne correspondent pas à une offre disponible.':p.public?'Annonce publiée par '+esc(p.seller)+'. La disponibilité est à confirmer avec son auteur. La validation ne constitue pas une garantie sur le vendeur.':'Votre annonce est enregistrée sur cet appareil. Elle n’est pas publiée et n’est pas visible par les autres visiteurs.'}</div><div class="detail-actions"><button class="m-secondary" type="button" data-favorite="${esc(p.id)}" aria-pressed="${isFav}">${isFav?'♥ En favori':'♡ Garder en favori'}</button>${p.public?'<a class="m-button" href="'+esc(p.issueUrl)+'" target="_blank" rel="noopener noreferrer">Échanger sur GitHub ↗</a>':p.example?'<button class="m-button" type="button" data-template="'+esc(p.id)+'">Préparer mon annonce</button>':'<button class="m-button" type="button" data-propose="'+esc(p.id)+'">Proposer à la communauté</button><button class="m-secondary" type="button" data-copy-listing="'+esc(p.id)+'">Copier pour partager</button><button class="m-secondary" type="button" data-edit="'+esc(p.id)+'">Modifier</button><button class="m-text-button" type="button" data-delete="'+esc(p.id)+'">Supprimer</button>'}</div></div></div>`;$('product-dialog').dataset.item=p.id;if(!$('product-dialog').open)openDialog('product-dialog')}
function toggleFavorite(id){const next=new Set(favorites);next.has(id)?next.delete(id):next.add(id);if(!write(FAV,[...next]))return notify('Stockage indisponible : le favori n’a pas été enregistré.');favorites=next;render();if($('product-dialog').open&&$('product-dialog').dataset.item===id){const p=item(id);detail(p);$('product-detail').querySelector('[data-favorite]').focus()}}
async function copyListing(p){const text=[p.title,p.description,priceText(p),p.location,p.condition,'Annonce préparée avec MTP — à confirmer avec son auteur.','https://mtptoken.pages.dev/echanges/'].filter(Boolean).join('\n');try{await navigator.clipboard.writeText(text);notify('Texte copié. Vous pouvez le partager vous-même.')}catch{notify('Copie indisponible. Exportez vos annonces pour conserver le texte.')}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!b.closest('#market-app'))return;const d=b.dataset;
 if('view'in d){setView(d.view);$('market-catalog').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
 if('create'in d)edit();if('reset'in d)reset();if('category'in d){$('filter-category').value=d.category;render()}
 if('close'in d)closeDialog(d.close);if('favorite'in d&&item(d.favorite))toggleFavorite(d.favorite);if('open'in d&&item(d.open))detail(item(d.open));
 if('template'in d){const p=item(d.template);closeDialog('product-dialog');edit();$('draft-category').value=p.category;$('draft-condition').value=p.condition}
 if('propose'in d){const p=drafts.find(x=>x.id===d.propose);if(p){closeDialog('product-dialog');proposal(p)}}
 if('edit'in d){const p=drafts.find(x=>x.id===d.edit);if(p){closeDialog('product-dialog');edit(p)}}
 if('delete'in d){pendingDelete=d.delete;closeDialog('product-dialog');openDialog('delete-dialog')}
 if('copyListing'in d){const p=drafts.find(x=>x.id===d.copyListing);if(p)copyListing(p)}
 if('removePhoto'in d&&!processing){photos.splice(Number(d.removePhoto),1);photoPreview()}
 if('photoIndex'in d){const p=item(d.item),n=Number(d.photoIndex);if(p?.photos[n]){$('detail-picture').innerHTML=`<img src="${p.photos[n]}" alt="${esc(p.title)} — photo ${n+1}">`;document.querySelectorAll('[data-photo-index]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}}
});
$('market-search').addEventListener('submit',e=>{e.preventDefault();render();$('market-catalog').scrollIntoView({block:'start'})});for(const id of ['market-query','market-location','filter-price'])$(id).addEventListener('input',render);for(const id of ['filter-category','filter-condition','filter-currency','filter-free','market-sort'])$(id).addEventListener('change',render);$('reset-filters').onclick=reset;
$('draft-free').onchange=()=>{$('draft-price').disabled=$('draft-free').checked};
$('listing-dialog').addEventListener('close',()=>{photoEpoch++;processing=false});
async function processPhoto(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Format non pris en charge. Choisissez JPG, PNG ou WebP.');if(file.size>8*1024*1024)throw Error('Une image dépasse 8 Mo. Choisissez un fichier plus léger.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>50000000)throw Error('Image trop grande. Réduisez ses dimensions.');const scale=Math.min(1,900/img.naturalWidth,900/img.naturalHeight),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let data=canvas.toDataURL('image/jpeg',.76);if(data.length>450000)data=canvas.toDataURL('image/jpeg',.5);if(data.length>450000)throw Error('Image encore trop volumineuse. Choisissez une image plus simple.');return data}finally{URL.revokeObjectURL(url)}}
$('draft-photos').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;if(files.length+photos.length>4){$('draft-status').textContent='Vous pouvez ajouter quatre photos maximum.';e.target.value='';return}const epoch=photoEpoch;processing=true;$('draft-save').disabled=true;$('draft-photos').disabled=true;$('draft-status').textContent='Préparation des photos…';try{const added=[];for(const file of files)added.push(await processPhoto(file));if(epoch!==photoEpoch)return;photos.push(...added);photoPreview();$('draft-status').textContent=added.length+' photo(s) prête(s).'}catch(err){if(epoch===photoEpoch)$('draft-status').textContent=err.message||'Impossible de lire cette image.'}finally{if(epoch===photoEpoch){processing=false;$('draft-save').disabled=false;$('draft-photos').disabled=false;$('draft-photos').value=''}}});
$('market-listing-form').addEventListener('submit',e=>{e.preventDefault();if(processing)return;const old=drafts.find(x=>x.id===$('edit-id').value);if(!old&&drafts.length>=MAX){$('draft-status').textContent='Limite de 100 annonces atteinte. Exportez puis retirez les annonces inutiles.';return}const next=normalize({id:old?.id||crypto.randomUUID(),title:$('draft-title').value,description:$('draft-description').value,category:$('draft-category').value,condition:$('draft-condition').value,price:$('draft-free').checked?'0':$('draft-price').value,currency:$('draft-currency').value,location:$('draft-location').value,free:$('draft-free').checked,photos,createdAt:old?.createdAt||Date.now()});if(!next){$('draft-status').textContent='Vérifiez le titre, la description et le prix de votre annonce.';return}const list=old?drafts.map(p=>p.id===old.id?next:p):[next,...drafts];if(!write(KEY,list)){$('draft-status').textContent='Stockage plein ou indisponible. Retirez des photos ou exportez vos anciennes annonces. Votre saisie reste ouverte.';return}drafts=list;closeDialog('listing-dialog');view='mine';reset();notify(old?'Annonce modifiée sur cet appareil.':'Annonce enregistrée sur cet appareil, non publiée.');$('market-catalog').scrollIntoView({block:'start'})});
$('confirm-delete').onclick=()=>{const next=drafts.filter(p=>p.id!==pendingDelete);if(!write(KEY,next)){closeDialog('delete-dialog');notify('Suppression impossible : stockage indisponible.');return}drafts=next;favorites.delete(pendingDelete);write(FAV,[...favorites]);pendingDelete=null;closeDialog('delete-dialog');render();notify('Annonce supprimée de cet appareil.')};
$('export-listings').onclick=()=>{if(!drafts.length)return notify('Aucune annonce à exporter pour le moment.');const blob=new Blob([JSON.stringify({format:'mtp-marketplace',version:1,exportedAt:new Date().toISOString(),listings:drafts},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mes-annonces-mtp-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Sauvegarde de vos annonces préparée.')};
$('import-listings').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>12*1024*1024)throw Error('La sauvegarde dépasse 12 Mo.');const parsed=JSON.parse(await file.text());if(parsed?.format!=='mtp-marketplace'||parsed.version!==1||!Array.isArray(parsed.listings))throw Error('Ce fichier n’est pas une sauvegarde MTP reconnue.');const incoming=normalizeList(parsed.listings);if(incoming.length!==parsed.listings.length)throw Error('La sauvegarde contient une annonce invalide. Aucun import effectué.');const ids=new Set(drafts.map(p=>p.id));const unique=[];for(const p of incoming)if(!ids.has(p.id)){unique.push(p);ids.add(p.id)}if(drafts.length+unique.length>MAX)throw Error('L’import dépasserait la limite de 100 annonces.');if(!unique.length)return notify('Ces annonces sont déjà présentes, ou la sauvegarde est vide.');const next=[...unique,...drafts];if(!write(KEY,next))throw Error('Stockage plein ou indisponible. L’import n’a pas été enregistré.');drafts=next;view='mine';reset();notify(unique.length+' annonce(s) importée(s). Vos annonces existantes sont conservées.')}catch(err){notify(err instanceof SyntaxError?'Le fichier JSON est illisible. Aucun import effectué.':err.message)}finally{e.target.value=''}});
window.addEventListener('storage',e=>{if(e.key===KEY){drafts=normalizeList(read(KEY,[]));render()}if(e.key===FAV){const f=read(FAV,[]);favorites=new Set(Array.isArray(f)?f:[]);render()}});
async function loadCatalog(force=false){
 if(catalogBusy)return;if(force&&Date.now()-lastFetch<30000){notify('Patientez quelques secondes avant une nouvelle actualisation.');return}catalogBusy=true;lastFetch=Date.now();$('refresh-catalog').disabled=true;$('public-status').textContent='Lecture du catalogue public…';
 try{const r=await fetch('https://raw.githubusercontent.com/jedi566666/MontpellierECU/main/marketplace/catalog.json',{signal:AbortSignal.timeout(12000),cache:force?'reload':'default'});if(!r.ok)throw Error();const data=await r.json();if(data.version!==1||!Array.isArray(data.listings))throw Error();publicListings=data.listings.map(p=>{if(!p||!Number.isInteger(p.number)||p.number<=0)return null;const n=normalize({...p,id:'github-'+p.number,photos:[]});if(!n)return null;return {...n,public:true,number:p.number,seller:typeof p.seller==='string'?p.seller.slice(0,80):'Auteur GitHub',photos:Array.isArray(p.photos)?p.photos.filter(s=>typeof s==='string'&&/^https:\/\/github\.com\/user-attachments\/assets\/[0-9a-f-]{36}$/i.test(s)).slice(0,4):[],issueUrl:'https://github.com/jedi566666/MontpellierECU/issues/'+p.number}}).filter(Boolean);$('public-status').textContent='Catalogue public consulté à '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})+' · mises à jour après validation.';render();}
 catch{$('public-status').textContent=publicListings.length?'Actualisation indisponible. Les dernières annonces chargées restent affichées.':'Catalogue public momentanément indisponible. Vos annonces locales et les exemples restent accessibles.';}
 finally{catalogBusy=false;$('refresh-catalog').disabled=false;}
}
function proposal(p){const data={title:p.title,description:p.description,category:p.category,condition:p.condition,price:p.price,currency:p.currency,location:p.location,free:p.free};$('proposal-text').value='Annonce proposée au marché MTP. Merci de la relire avant publication.\n\n'+'```mtp-marketplace\n'+JSON.stringify(data,null,2)+'\n```\n\nPhotos : ajouter ici les pièces jointes GitHub (4 maximum).\n\nJe confirme que cette proposition est publique et respecte la charte du marché.';$('open-proposal').href='https://github.com/jedi566666/MontpellierECU/issues/new?template=marketplace.md&title='+encodeURIComponent('[Annonce] '+p.title);$('proposal-status').textContent='';openDialog('proposal-dialog')}
$('copy-proposal').onclick=async()=>{try{await navigator.clipboard.writeText($('proposal-text').value);$('proposal-status').textContent='Texte copié. Collez-le dans la proposition GitHub.'}catch{$('proposal-text').select();$('proposal-status').textContent='Sélectionnez puis copiez le texte manuellement.'}};
$('refresh-catalog').onclick=()=>loadCatalog(true);
render();loadCatalog();if(storageProblem)notify('Les données locales sont indisponibles ou illisibles. Exportez vos annonces dès que possible.');
})();
