import { initMarketBanner } from './market-banner.js';
import { initScreenIntro } from './screen-intro.js';
import { initChart } from './chart.js';
import { publicJson } from './market-data.js';
import { initLiveTools } from './live-tools.js';
import QRCode from 'qrcode';
const TOKEN='0x50626097a780881d3dFf1Ff97579e6dAF965366B',RPC='https://mainnet.base.org';
const $=id=>document.getElementById(id);
const validAddress=value=>/^0x[a-fA-F0-9]{40}$/.test(value);
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
const remove=key=>{try{localStorage.removeItem(key)}catch{}};
let toastTimer;
function toast(message){$('toast').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4500)}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copié dans le presse-papiers.')}catch{toast('Copie impossible. Sélectionnez le texte pour le copier.')}}
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copy(b.dataset.copy)));
async function json(url,options={}){if(!options.method&&/^https:\/\/api\.(geckoterminal|dexscreener)\.com\//.test(url))return publicJson(url);const r=await fetch(url,{...options,signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function rpc(method,params){const r=await json(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});if(r.error||r.result==null)throw Error('Réponse RPC indisponible');return r.result}
function units(hex){if(!/^0x[0-9a-f]+$/i.test(hex))throw Error('Solde invalide');const n=BigInt(hex),d=10n**18n;const whole=(n/d).toLocaleString('fr-FR'),fraction=(n%d).toString().padStart(18,'0').replace(/0+$/,'');return whole+(fraction?(new Intl.NumberFormat('fr-FR').formatToParts(1.1).find(p=>p.type==='decimal')?.value||'.')+fraction:'')}
function wallet(){let account=null,mode='watch',epoch=0,busy=false;const provider=window.ethereum;const status=(text,error=false)=>{$('wallet-status').textContent=text;$('wallet-status').classList.toggle('error',error)};
 function clear(){epoch++;account=null;busy=false;remove('mtp.web.address');$('mtp-balance').textContent='—';$('eth-balance').textContent='—';$('active-address').textContent='—';$('wallet-mode').textContent='Non connecté';$('receive-qr').hidden=true;$('receive-empty').hidden=false;$('copy-address').disabled=true;$('explorer-address').hidden=true;$('address').value='';status('Session locale effacée. Les autorisations se gèrent dans votre portefeuille.');}
 async function load(address,nextMode='watch'){if(!validAddress(address)){status('Saisissez une adresse Base valide (0x et 40 caractères hexadécimaux).',true);return}const mine=++epoch;busy=true;account=address;mode=nextMode;$('address').value=address;save('mtp.web.address',address);$('wallet-mode').textContent=mode==='injected'?'Wallet connecté · Base':'Lecture seule · Base';$('active-address').textContent=address.slice(0,8)+'…'+address.slice(-6);$('copy-address').disabled=false;$('explorer-address').href='https://basescan.org/address/'+address;$('explorer-address').hidden=false;$('mtp-balance').textContent='—';$('eth-balance').textContent='—';status('Lecture des soldes sur Base…');
 try{const data=await QRCode.toDataURL(address,{width:180,margin:2,errorCorrectionLevel:'M'});if(mine!==epoch)return;const img=new Image();img.onload=()=>{if(mine!==epoch)return;const c=$('receive-qr');c.width=180;c.height=180;c.getContext('2d').drawImage(img,0,0,180,180);c.hidden=false;$('receive-empty').hidden=true};img.src=data;}catch{if(mine===epoch){$('receive-qr').hidden=true;$('receive-empty').hidden=false;$('receive-empty').textContent='QR indisponible. Copiez votre adresse publique.'}}
 const values=await Promise.allSettled([rpc('eth_call',[{to:TOKEN,data:'0x70a08231'+address.slice(2).toLowerCase().padStart(64,'0')},'latest']),rpc('eth_getBalance',[address,'latest'])]);if(mine!==epoch)return;let fails=0;for(let i=0;i<values.length;i++){try{if(values[i].status!=='fulfilled')throw Error();$(i===0?'mtp-balance':'eth-balance').textContent=units(values[i].value)}catch{fails++}}busy=false;status(fails?'Certaines données sont indisponibles. Réessayez pour relire les soldes.':'Soldes lus sur Base à '+new Date().toLocaleTimeString('fr-FR')+'.',fails>0);}
 $('watch-form').addEventListener('submit',e=>{e.preventDefault();load($('address').value.trim())});$('refresh-wallet').addEventListener('click',()=>{if(account&&!busy)load(account,mode);else if(!account)status('Connectez un portefeuille ou saisissez une adresse publique.')});$('copy-address').addEventListener('click',()=>account&&copy(account));$('disconnect').addEventListener('click',clear);
 $('connect').addEventListener('click',async()=>{if(!provider?.request){status('Aucun portefeuille détecté. Ouvrez ce site dans le navigateur de votre Wallet ou utilisez une extension compatible avec Base.',true);return}$('connect').disabled=true;try{let chain=await provider.request({method:'eth_chainId'});if(chain!=='0x2105'){try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x2105'}]})}catch(e){if(e.code!==4902)throw e;await provider.request({method:'wallet_addEthereumChain',params:[{chainId:'0x2105',chainName:'Base',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:[RPC],blockExplorerUrls:['https://basescan.org']}]})}}chain=await provider.request({method:'eth_chainId'});if(chain!=='0x2105')throw Error('Sélectionnez le réseau Base dans votre Wallet.');const accounts=await provider.request({method:'eth_requestAccounts'});if(!accounts?.length)throw Error('Aucun compte partagé.');await load(accounts[0],'injected')}catch(e){status(e.code===4001?'Connexion annulée dans le portefeuille.':e.message||'Connexion impossible.',true)}finally{$('connect').disabled=false}});
 provider?.on?.('accountsChanged',accounts=>{if(mode!=='injected')return;if(!accounts.length)clear();else load(accounts[0],'injected')});provider?.on?.('chainChanged',chain=>{if(mode==='injected'&&chain!=='0x2105'){clear();status('Réseau changé. Reconnectez le portefeuille sur Base.',true)}});
 const previous=read('mtp.web.address',null);if(typeof previous==='string'&&validAddress(previous))load(previous);
}
const number=v=>v===null||v===undefined||v===''?null:Number.isFinite(Number(v))&&Number(v)>=0?Number(v):null;
const usd=(v,price=false)=>v===null?'—':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD',maximumFractionDigits:price?10:2}).format(v);
function live(){let busy=false;async function refresh(){if(busy)return;busy=true;$('refresh-live').disabled=true;$('live-status').textContent='Interrogation des sources…';['pool-count','pool-liquidity','pool-volume'].forEach(id=>$(id).textContent='—');$('pools').replaceChildren();const endpoints=[['GeckoTerminal','https://api.geckoterminal.com/api/v2/networks/base/tokens/'+TOKEN+'/pools?page=1'],['DexScreener','https://api.dexscreener.com/token-pairs/v1/base/'+TOKEN]];const results=await Promise.allSettled(endpoints.map(([,url])=>json(url)));let pools=new Map(),states=[],successful=0;
 results.forEach((r,i)=>{const source=endpoints[i][0];if(r.status==='rejected'){states.push(source+' : indisponible');return}const rows=i===0?r.value.data:r.value;if(!Array.isArray(rows)){states.push(source+' : réponse invalide');return}successful++;states.push(source+' : '+rows.length+' pool(s) retournée(s)');for(const p of rows){let item;if(i===0){const a=p.attributes||{},rel=p.relationships||{},baseToken=rel.base_token?.data?.id?.toLowerCase(),quoteToken=rel.quote_token?.data?.id?.toLowerCase(),t='base_'+TOKEN.toLowerCase();if(baseToken!==t&&quoteToken!==t)continue;item={id:a.address,name:a.name,dex:rel.dex?.data?.id,price:number(baseToken===t?a.base_token_price_usd:a.quote_token_price_usd),liquidity:number(a.reserve_in_usd),volume:number(a.volume_usd?.h24),source,url:'https://www.geckoterminal.com/base/pools/'+a.address}}else{if(p.chainId!=='base')continue;const isBase=p.baseToken?.address?.toLowerCase()===TOKEN.toLowerCase(),isQuote=p.quoteToken?.address?.toLowerCase()===TOKEN.toLowerCase();if(!isBase&&!isQuote)continue;item={id:p.pairAddress,name:(p.baseToken?.symbol||'?')+' / '+(p.quoteToken?.symbol||'?'),dex:p.dexId,price:isBase?number(p.priceUsd):null,liquidity:number(p.liquidity?.usd),volume:number(p.volume?.h24),source,url:'https://dexscreener.com/base/'+p.pairAddress}}if(!/^0x[a-fA-F0-9]{40}([a-fA-F0-9]{24})?$/.test(item.id||''))continue;const key=item.id.toLowerCase();if(!pools.has(key))pools.set(key,item)}});
 const list=[...pools.values()].sort((a,b)=>(b.liquidity??-1)-(a.liquidity??-1));$('pool-count').textContent=successful?list.length:'—';document.dispatchEvent(new CustomEvent('mtp:pools',{detail:list}));const sum=field=>list.length&&list.every(p=>p[field]!==null)?list.reduce((s,p)=>s+p[field],0):null;$('pool-liquidity').textContent=usd(sum('liquidity'));$('pool-volume').textContent=usd(sum('volume'));for(const p of list){const tr=document.createElement('tr');const name=document.createElement('td');name.textContent=p.name||'Pool MTP';const sub=document.createElement('div');sub.className='label';sub.textContent=p.dex||'Plateforme inconnue';name.append(sub);tr.append(name);for(const v of [usd(p.price,true),usd(p.liquidity),usd(p.volume)]){const td=document.createElement('td');td.textContent=v;tr.append(td)}const td=document.createElement('td'),a=document.createElement('a');a.href=p.url;a.textContent=p.source+' ↗';td.append(a);tr.append(td);$('pools').append(tr)}if(!list.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.className='empty';td.textContent=successful?'Aucune pool MTP retournée par les sources disponibles. Cela ne prouve pas l’absence du token sur Base.':'Sources momentanément indisponibles. Réessayez dans quelques instants.';tr.append(td);$('pools').append(tr)}$('live-status').textContent=(successful?'Sources consultées':'Échec de consultation')+' à '+new Date().toLocaleTimeString('fr-FR')+' · actualisation automatique · 60 s';$('source-details').textContent=states.join(' · ')+'. GeckoTerminal : première page (20 pools maximum). Doublons regroupés par identifiant de pool ; GeckoTerminal prioritaire. Totaux non affichés si une valeur manque.';$('refresh-live').disabled=false;busy=false}
 $('refresh-live').addEventListener('click',refresh);refresh();
}
function exchanges(){const key='mtp.web.listings';let stored=read(key,[]),list=Array.isArray(stored)?stored.filter(p=>p&&typeof p.title==='string'&&typeof p.description==='string'&&typeof p.id==='string'):[];function render(){$('listings').replaceChildren();if(!list.length){const p=document.createElement('p');p.className='status';p.textContent='Aucun brouillon pour le moment. Votre prochaine idée commence au-dessus.';$('listings').append(p)}for(const item of list){const card=document.createElement('article');card.className='listing';const tag=document.createElement('span');tag.className='local-tag';tag.textContent=item.type+' · local';const h=document.createElement('h3');h.textContent=item.title;const p=document.createElement('p');p.className='status';p.textContent=item.description;const price=document.createElement('p');price.className='label';price.textContent=item.price!==''&&item.price!=null?item.price+' MTP':'Montant à convenir';const row=document.createElement('div');row.className='row';const c=document.createElement('button');c.className='button secondary';c.textContent='Copier pour partager';c.onclick=()=>copy(item.title+'\n'+item.description+'\n'+price.textContent+'\nMontpellier ECU · https://mtptoken.pages.dev/echanges/');const d=document.createElement('button');d.className='button secondary';d.textContent='Supprimer';d.onclick=()=>{const next=list.filter(p=>p.id!==item.id);if(save(key,next)){list=next;render()}else toast('Stockage indisponible. Suppression non enregistrée.')};row.append(c,d);card.append(tag,h,p,price,row);$('listings').append(card)}}$('listing-form').addEventListener('submit',e=>{e.preventDefault();const item={id:crypto.randomUUID(),title:$('listing-title').value.trim(),description:$('listing-description').value.trim(),type:$('listing-type').value,price:$('listing-price').value};if(!item.title||!item.description)return;const next=[item,...list];if(!save(key,next)){$('listing-status').textContent='Stockage indisponible. Votre brouillon n’a pas été enregistré.';return}list=next;render();e.target.reset();$('listing-status').textContent='Brouillon enregistré sur cet appareil. Il n’est pas publié.'});render()}
if($('watch-form'))wallet();if($('pools')){initChart();initLiveTools();live();}if($('listing-form'))exchanges();


initScreenIntro();
initMarketBanner();
