const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'site');
const base='https://mtptoken.pages.dev';
const token='0x50626097a780881d3dFf1Ff97579e6dAF965366B';
const link=(href,text,cls='button secondary')=>`<a class="${cls}" href="${href}">${text}</a>`;
const contract=`<div class="contract-box"><div class="label">Contrat officiel · Base</div><p class="contract">${token}</p><div class="row"><button class="button secondary" data-copy="${token}">Copier le contrat</button>${link('https://basescan.org/token/'+token,'Vérifier sur BaseScan ↗','textlink')}</div></div>`;
const pages={
 '/':{title:'Montpellier ECU — Une autre idée de la valeur.',description:'Découvrez Montpellier ECU : une communauté occitane, le token MTP sur Base, un Wallet et un observatoire des marchés réunis au même endroit.',content:`
 <section class="hero"><div class="eyebrow reveal"><span class="dot"></span>Né à Montpellier. Ouvert sur le monde.</div><h1 class="reveal">Une autre idée<br>de <em>la valeur.</em></h1><p class="lede">Des personnes. Des échanges. Un territoire.<br>Découvrez l’écosystème Montpellier ECU.</p><div class="actions">${link('/wallet/','Découvrir le Wallet <span>↗</span>','button')}${link('#ecosysteme','Explorer MTP <span>↓</span>')}</div><div class="coin-stage"><div class="orbit-label">L’IDENTITÉ<b>Racines occitanes.</b></div><img src="/assets/coin.png" alt="Pièce Montpellier ECU, or et croix occitane rouge" width="335" height="335" fetchpriority="high"><div class="orbit-label right">LE RÉSEAU<b>Construit sur Base.</b></div></div></section>
 <div class="wrap"><div class="proof-strip"><strong>MONTPELLIER ECU</strong><span>Base · Ethereum L2</span><span>Token ERC-20 · 18 décimales</span><span>Identité occitane. Ambition collective.</span></div>
 <section class="section" id="ecosysteme"><div class="section-head"><div><div class="eyebrow">Un écosystème. Trois portes d’entrée.</div><h2>Tout MTP.<br><em>Au même endroit.</em></h2></div><p>Comprendre le projet, retrouver ses MTP et observer l’activité. Chaque espace a son rôle. Tout reste connecté.</p></div><div class="grid">
 <article class="card"><span class="card-num">01 / UTILISER</span><div class="card-visual" aria-hidden="true"><div class="mini-wallet">MONTPELLIER ECU<strong>MTP Wallet</strong>BASE NETWORK <span style="float:right">◈</span></div></div><h3>Votre MTP.<br>Votre Wallet.</h3><p>Connectez votre portefeuille ou consultez une adresse publique. Vos actifs restent sous votre contrôle.</p>${link('/wallet/','Ouvrir le Wallet ↗','textlink')}</article>
 <article class="card"><span class="card-num">02 / OBSERVER</span><div class="card-visual" aria-hidden="true"><div class="bars">${'<span></span>'.repeat(7)}</div></div><div class="visual-caption">Illustration · aucune donnée de marché</div><h3>Le mouvement.<br>En toute clarté.</h3><p>Pools, liquidité et activité : des données sourcées, avec leur état de disponibilité.</p>${link('/live/','Explorer MTP Live ↗','textlink')}</article>
 <article class="card"><span class="card-num">03 / ÉCHANGER</span><div class="card-visual" aria-hidden="true"><span class="cross">✥</span></div><h3>Plus proche.<br>Plus humain.</h3><p>Des objets, du temps, des compétences. Préparez une annonce et rejoignez la communauté.</p>${link('/echanges/','Découvrir les échanges ↗','textlink')}</article></div></section>
 <section class="story" id="vision"><div><div class="eyebrow">L’esprit Montpellier ECU</div><h2>Une monnaie n’a de sens<br>que par <em>ce qu’elle relie.</em></h2><p>MTP est né d’une envie simple : redonner une place aux échanges concrets. Aux personnes qui fabriquent, réparent, transmettent et s’entraident.</p><p>Une identité occitane. Un outil numérique sur Base. Et une communauté à construire, échange après échange.</p>${link('https://t.me/MTPOCCITANIE','Rejoindre la communauté ↗','textlink')}</div><img src="/assets/world.png" alt="Univers graphique Montpellier ECU, un réseau relié au monde" loading="lazy" width="640" height="360"></section>
 <section class="section"><div class="section-head"><div><div class="eyebrow">Argent 0</div><h2>La richesse commence<br><em>avant l’argent.</em></h2></div><p>Un objet inutilisé. Un savoir-faire. Une heure donnée. La philosophie Argent 0 remet l’usage et le lien au centre de la valeur.</p></div><div class="grid"><article class="card"><span class="eyebrow">Les objets</span><h3>Faire circuler.</h3><p>Prolonger la vie de ce qui existe, donner une seconde utilité aux objets du quotidien.</p></article><article class="card"><span class="eyebrow">Les savoir-faire</span><h3>Transmettre.</h3><p>Partager une compétence, rendre un service et reconnaître le temps de chacun.</p></article><article class="card"><span class="eyebrow">Les rencontres</span><h3>Créer du lien.</h3><p>Partir du local pour construire des échanges accessibles et une communauté vivante.</p></article></div></section>
 <section class="story"><div><div class="eyebrow">Monia · Windows</div><h2>L’univers MTP.<br><em>Sur votre bureau.</em></h2><p>Monia rassemble les outils MTP dans une application Windows. La version publiée est disponible sur le dépôt officiel.</p>${link('https://github.com/jedi566666/MontpellierECU/releases','Voir les versions publiées ↗','button secondary')}</div><div><div class="quote">Un point d’entrée.<br>Tout un univers.</div><p>Wallet, Live, échanges et communauté.</p><span class="local-tag">Application Windows</span></div></section>
 <section class="section" id="transparence"><div class="section-head"><div><div class="eyebrow">Vérifier. Comprendre.</div><h2>La confiance mérite<br><em>de la transparence.</em></h2></div><p>Le contrat officiel est public. Consultez le code et l’activité sur l’explorateur du réseau Base.</p></div><div class="details"><div><strong>Base</strong><span>Réseau · identifiant 8453</span></div><div><strong>ERC-20</strong><span>Standard du token</span></div><div><strong>18</strong><span>Décimales</span></div></div>${contract}<p class="notice">MTP n’est pas une promesse de rendement. Un prix affiché par une pool ne garantit pas qu’un échange soit réalisable à ce prix. Consultez les données et la liquidité dans MTP Live.</p><details><summary>Où retrouver mes MTP ?</summary><p>Dans l’espace Wallet, connectez un portefeuille compatible avec Base ou saisissez votre adresse publique pour consulter son solde. Aucune phrase de récupération n’est demandée.</p></details><details><summary>Pourquoi plusieurs pages ?</summary><p>L’accueil présente le projet, Wallet permet de consulter vos actifs et Live montre les données des pools. Les échanges disposent aussi de leur espace dédié.</p></details><details><summary>Les annonces sont-elles publiées automatiquement ?</summary><p>Non. L’espace Échanges conserve vos brouillons sur cet appareil. Vous pouvez les copier puis les partager vous-même dans la communauté.</p></details></section></div>`},
 '/wallet/':{title:'MTP Wallet — Votre MTP, sous votre contrôle.',description:'Consultez votre solde Montpellier ECU sur Base, connectez votre portefeuille et partagez votre adresse de réception.',content:`<div class="wrap"><section class="page-hero"><div class="eyebrow"><span class="dot"></span>MTP Wallet · Base</div><h1>Votre MTP.<br><em>Sous votre contrôle.</em></h1><p>Un accès simple à votre adresse et à vos soldes sur Base.<br>Connectez votre portefeuille, ou regardez simplement.</p></section><div class="workspace"><section class="panel"><div class="row" style="justify-content:space-between"><span class="label">Votre solde</span><span class="local-tag" id="wallet-mode">Non connecté</span></div><div class="balance"><span id="mtp-balance">—</span> <small>MTP</small></div><div class="label"><span id="eth-balance">—</span> ETH · réseau Base</div><div class="row"><button id="connect" class="button">Connecter un Wallet ↗</button><button id="refresh-wallet" class="button secondary">Actualiser</button></div><p id="wallet-status" class="status" role="status">Aucun portefeuille connecté.</p><form id="watch-form"><label for="address">Ou consulter une adresse publique</label><input id="address" autocomplete="off" spellcheck="false" placeholder="0x…" aria-describedby="watch-help" required pattern="0x[a-fA-F0-9]{40}"><p class="label" id="watch-help">Lecture seule : aucune signature ni transaction.</p><button class="button secondary" type="submit">Consulter cette adresse →</button></form><div class="wallet-meta"><span class="label">Adresse active</span><span id="active-address">—</span></div><div class="row"><button id="copy-address" class="button secondary" disabled>Copier l’adresse</button><a id="explorer-address" class="textlink" hidden>Explorer ↗</a><button id="disconnect" class="button secondary">Effacer la session locale</button></div></section><section class="panel"><div class="eyebrow">Recevoir</div><h2>Une adresse.<br>Un lien direct.</h2><p class="status">Partagez votre adresse publique pour recevoir des MTP sur le réseau Base.</p><canvas id="receive-qr" class="qr" hidden aria-label="QR code de votre adresse publique"></canvas><p id="receive-empty" class="notice">Votre QR code apparaît après la connexion ou la consultation d’une adresse.</p><p class="status">Le QR code contient l’adresse publique uniquement. Vérifiez que l’expéditeur utilise Base et le contrat MTP officiel.</p>${contract}</section></div></div>`},
 '/live/':{title:'MTP Live — Observer Montpellier ECU sur Base.',description:'Consultez les pools MTP sur Base, leur liquidité et leur volume. Données GeckoTerminal et DexScreener, avec sources et horodatage.',content:`<div class="wrap"><section class="page-hero"><div class="eyebrow"><span class="dot"></span>L’observatoire MTP</div><h1>Voir le mouvement.<br><em>Comprendre les données.</em></h1><p>Les pools de Montpellier ECU, réunies dans une vue claire. Des sources publiques. Aucune courbe inventée.</p></section><div class="row" style="justify-content:space-between"><p id="live-status" class="status" role="status">Chargement des sources publiques…</p><button id="refresh-live" class="button secondary">Actualiser ↻</button></div><div class="stats"><div class="stat"><div class="label">Pools retournées</div><strong id="pool-count">—</strong><small>Par les sources disponibles</small></div><div class="stat"><div class="label">Liquidité cumulée</div><strong id="pool-liquidity">—</strong><small>USD · pools affichées</small></div><div class="stat"><div class="label">Volume sur 24 h</div><strong id="pool-volume">—</strong><small>USD · pools affichées</small></div></div><p class="notice">Les données affichées ne constituent pas un prix garanti. Une faible liquidité peut empêcher un échange ou provoquer un écart de prix important. « — » signifie que la donnée est indisponible.</p><div class="table-wrap"><table><caption class="skip">Pools MTP sur Base et données de marché</caption><thead><tr><th>Pool / plateforme</th><th>Prix indicatif MTP</th><th>Liquidité</th><th>Volume 24 h</th><th>Source</th></tr></thead><tbody id="pools"><tr><td colspan="5" class="empty">Interrogation de GeckoTerminal et DexScreener…</td></tr></tbody></table></div><section class="story" style="margin-bottom:70px"><div><div class="eyebrow">La lecture juste</div><h2>Un chiffre mérite<br><em>son contexte.</em></h2><p>Une pool n’est pas une promesse de liquidité. Une absence sur un agrégateur ne signifie pas que le token a disparu. Les réponses des sources sont affichées sans remplacer les valeurs manquantes par des estimations.</p></div><div>${contract}<p class="status" id="source-details"></p></div></section></div>`},
 '/echanges/':{title:'Échanges MTP — Objets, services et savoir-faire.',description:'Préparez vos annonces Montpellier ECU : objets, services, compétences et dons. Conservez vos brouillons puis partagez-les dans la communauté.',content:`<div class="wrap"><section class="page-hero"><div class="eyebrow">La valeur des choses simples</div><h1>Moins d’inutilisé.<br><em>Plus de possibilités.</em></h1><p>Un objet à transmettre. Une compétence à partager.<br>Préparez votre annonce et donnez une suite à vos idées.</p></section><div class="workspace"><section class="panel"><h2>Votre prochaine annonce.</h2><span class="local-tag">Brouillon local · non publié</span><form id="listing-form"><label for="listing-title">Titre</label><input id="listing-title" required maxlength="100" placeholder="Un vélo à remettre en circulation"><label for="listing-type">Catégorie</label><select id="listing-type"><option>Objet</option><option>Service</option><option>Savoir-faire</option><option>Don</option></select><label for="listing-description">Description</label><textarea id="listing-description" required maxlength="2000" placeholder="Décrivez votre proposition et votre localisation approximative."></textarea><label for="listing-price">Montant en MTP (facultatif)</label><input id="listing-price" type="number" min="0" step="any" placeholder="À convenir"><div class="row"><button type="submit" class="button">Enregistrer le brouillon</button></div><p id="listing-status" class="status" role="status"></p></form></section><section class="panel"><div class="eyebrow">Du local au collectif</div><h2>Une communauté<br>pour faire le lien.</h2><p class="status">Les annonces enregistrées ici restent dans ce navigateur. Copiez votre brouillon pour le partager vous-même avec la communauté.</p><div class="row">${link('https://t.me/MTPOCCITANIE','Ouvrir la communauté ↗','button secondary')}</div><p class="notice">Aucune commande, aucun paiement et aucune publication ne sont effectués depuis cette page. Les anciennes offres promotionnelles ne sont pas présentées comme disponibles sans confirmation de leur stock.</p><h3>Donner, réparer, transmettre.</h3><p class="status">L’esprit Argent 0 commence par reconnaître ce qui a déjà de la valeur autour de nous.</p></section></div><div class="section-head"><h2>Vos brouillons.</h2><span class="label">Enregistrés uniquement sur cet appareil</span></div><div class="grid listings" id="listings"></div></div>`},
 '/confidentialite/':{title:'Confidentialité — Montpellier ECU',description:'Comprendre les données utilisées par le site Montpellier ECU, le Wallet et MTP Live.',content:`<div class="wrap"><section class="page-hero"><div class="eyebrow">Vos données</div><h1>De la clarté.<br><em>Tout simplement.</em></h1></section><section class="panel" style="margin-bottom:70px"><h2>Stockage sur cet appareil</h2><p class="status">Votre dernière adresse consultée et vos brouillons d’annonces sont conservés dans le stockage local du navigateur. Le bouton « Effacer la session locale » du Wallet retire son adresse mémorisée. Les brouillons se suppriment individuellement dans Échanges. Effacer les données du site dans votre navigateur retire ces éléments.</p><h2>Sources et services externes</h2><p class="status">La consultation des soldes transmet l’adresse publique au RPC public de Base. MTP Live et le bandeau de marché interrogent GeckoTerminal et DexScreener pour les pools du contrat officiel. Le bandeau consulte également Blockscout pour les derniers transferts MTP. Ces services et Cloudflare, l’hébergeur, reçoivent les informations techniques nécessaires aux requêtes, dont votre adresse IP. Les liens externes ouvrent les services concernés uniquement à votre initiative.</p><h2>Portefeuille</h2><p class="status">La connexion demande au portefeuille les comptes que vous acceptez de partager. Ce site ne demande aucune phrase de récupération, aucune clé privée et ne conserve aucun secret de signature. La consultation du solde n’effectue aucune transaction.</p><h2>Mesure d’audience</h2><p class="status">Cette version ne contient aucun script publicitaire ni outil de mesure d’audience. Pour contacter le projet : <a class="textlink" href="https://t.me/MTPOCCITANIE">communauté MTP ↗</a>.</p></section></div>`}
};
function shell(route,p){const canonical=base+route;return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${p.title}</title><meta name="description" content="${p.description}"><meta name="theme-color" content="#080809"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="fr_FR"><meta property="og:title" content="${p.title}"><meta property="og:description" content="${p.description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${base}/assets/logo.png"><meta name="twitter:card" content="summary"><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script>${route==='/'?'<meta name="google-site-verification" content="dd5Q-tNJBukcYTLHoUMFdbqoDc57R21S3035zFzvjMk" /><meta name="google-site-verification" content="MABFo8y1xzkm4MTuhF6WV7j_XhvEeO0O50KjNvlZUIY" />':''}<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:p.title,description:p.description,url:canonical,inLanguage:'fr-FR',isPartOf:{'@type':'WebSite',name:'Montpellier ECU',url:base+'/'}})}</script></head><body data-page="${route}"><div class="occitan-intro" aria-hidden="true"><span class="occitan-intro-cross"></span><span class="occitan-intro-name">MTP<span>Montpellier ECU</span></span></div><a class="skip" href="#main">Aller au contenu</a><header><nav class="nav" aria-label="Navigation principale"><a class="brand" href="/"><img src="/assets/logo.png" alt="" width="34" height="34">MTP<small>MONTPELLIER ECU</small></a><div class="links">${[['/','Découvrir'],['/wallet/','Wallet'],['/live/','Live'],['/echanges/','Échanges']].map(([url,label])=>`<a href="${url}" ${url===route?'aria-current="page"':''}>${label}</a>`).join('')}</div><a class="nav-cta" href="https://t.me/MTPOCCITANIE">La communauté ↗</a></nav></header><main id="main">${p.content}</main><footer class="footer"><div class="wrap"><div class="footer-top"><div class="brand"><img src="/assets/logo.png" alt="" width="34" height="34">Montpellier ECU</div><nav aria-label="Liens utiles"><a href="/#vision">Le projet</a><a href="/#transparence">Transparence</a><a href="/documentation/">Documentation</a><a href="https://github.com/jedi566666/MontpellierECU">GitHub ↗</a><a href="https://t.me/MTPOCCITANIE">Communauté ↗</a></nav></div><div class="footer-bottom"><span>Montpellier ECU · Racines occitanes. Horizon ouvert.</span><a href="/confidentialite/">Confidentialité & données</a></div></div></footer><div id="toast" class="toast" role="status"></div></body></html>`}
pages['/documentation/']={title:'Documentation et preuves du contrat — MTP',description:'Fonctionnement réel du site Montpellier ECU et dossier reproductible du contrat officiel sur Base.',content:fs.readFileSync(path.join(__dirname,'documentation.html'),'utf8')};
pages['/coulisses/']={title:'Comment nous construisons la BD, le jeu et MTP — Montpellier ECU',description:'Le carnet de fabrication de l’écosystème Montpellier ECU : bande dessinée, jeu Godot, MTP Token, outils IA et leçons apprises.',content:fs.readFileSync(path.join(__dirname,'coulisses.html'),'utf8')};
for(const [route,p] of Object.entries(pages)){const dir=path.join(root,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),shell(route,p));}
fs.writeFileSync(path.join(root,'404.html'),shell('/404/',{title:'Page introuvable — MTP',description:'Retrouvez les espaces Montpellier ECU.',content:'<div class="wrap page-hero"><div class="eyebrow">404</div><h1>Un détour.<br>Pas une impasse.</h1><p>Cette page n’existe pas.</p><a class="button" href="/">Revenir à MTP →</a></div>'}).replace('<link rel="canonical" href="https://mtptoken.pages.dev/404/">','<meta name="robots" content="noindex">'));
fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: '+base+'/sitemap.xml\n');
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+Object.keys(pages).map(r=>'<url><loc>'+base+r+'</loc></url>').join('')+'</urlset>');
fs.writeFileSync(path.join(root,'_headers'),'/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src \'self\'; script-src \'self\' \'unsafe-inline\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data:; connect-src \'self\' https://mainnet.base.org https://api.geckoterminal.com https://api.dexscreener.com https://base.blockscout.com; frame-ancestors \'none\'; base-uri \'self\'; form-action \'self\'\n');
require('esbuild').buildSync({entryPoints:[path.join(__dirname,'app-source.js')],outfile:path.join(root,'app.js'),bundle:true,minify:true,platform:'browser',target:['es2020'],legalComments:'eof'});
console.log('Built '+Object.keys(pages).length+' pages in '+root);

require('./localized-pages.cjs')({fs,path,root,base,pages,shell});
require('./commerce-content.cjs')({fs,path,root});
require('./marketplace-content.cjs')({fs,path,root,shell,base});
require('./donations-content.cjs')({fs,path,root,shell,base});
require('./legal-content.cjs')({fs,path,root,shell,base});
require('./contact-content.cjs')({fs,path,root});
require('./premium-content.cjs')({fs,path,root});
require('./seo-finalize.cjs')({fs,path,root,base});
