import {updateHistoryContext} from './chart-freshness.js';
const TOKEN='0x50626097a780881d3dFf1Ff97579e6dAF965366B';
export function initChart(){
 const anchor=document.querySelector('#live-status')?.parentElement;if(!anchor)return;
 const panel=document.createElement('section');panel.className='gold-chart';panel.innerHTML=`<div class="chart-top"><div><div class="eyebrow"><span class="dot"></span>MTP / USD · Base</div><div class="chart-price" id="chart-price">—</div><div class="label">Prix indicatif de la pool sélectionnée</div></div><div class="chart-tools"><label for="chart-pool">Pool de référence</label><select id="chart-pool"><option>Chargement…</option></select><div class="chart-periods" role="group" aria-label="Période du graphique"><button data-period="1">24 h</button><button data-period="7">7 jours</button><button data-period="0" aria-pressed="true">Historique</button></div></div></div><div class="chart-readout" id="chart-readout">Survolez ou touchez la courbe pour lire un cours.</div><canvas id="gold-canvas" tabindex="0" role="img" aria-label="Historique du prix MTP en dollars. Les valeurs sont aussi disponibles dans le tableau ci-dessous."></canvas><p class="status" id="chart-status" role="status">En attente des pools…</p><div class="chart-bottom"><span>GeckoTerminal · clôtures horaires · USD</span><span>Actualisation automatique · 60 s</span></div><details><summary>Consulter les valeurs du graphique</summary><div class="chart-data"><table><thead><tr><th>Date</th><th>Clôture MTP / USD</th></tr></thead><tbody id="chart-data"></tbody></table></div></details>`;anchor.before(panel);
 const el=id=>document.getElementById(id),canvas=el('gold-canvas'),ctx=canvas.getContext('2d');let pools=[],selected='',points=[],period=0,seq=0,visible=[],geometry=null,lastFetch=0;
 const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD',maximumSignificantDigits:7}).format(n);
 const date=t=>new Date(t*1000).toLocaleString('fr-FR');
 function draw(){const w=canvas.clientWidth,h=320,dpr=window.devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const cutoff=period?Date.now()/1000-period*86400:0;visible=points.filter(p=>p[0]>=cutoff);geometry=null;ctx.font='11px system-ui';ctx.fillStyle='#88858a';if(!visible.length){ctx.textAlign='center';ctx.fillText('Aucun échange disponible sur cette période.',w/2,h/2);return}const left=14,right=w<500?80:110,top=25,bottom=40;let min=Math.min(...visible.map(p=>p[1])),max=Math.max(...visible.map(p=>p[1]));const pad=(max-min)*.12||Math.max(max*.03,.00000001);min=Math.max(0,min-pad);max+=pad;let start=visible[0][0],end=visible.at(-1)[0];if(start===end){start-=1800;end+=1800}const x=t=>left+(t-start)/(end-start)*(w-left-right),y=v=>top+(max-v)/(max-min)*(h-top-bottom);geometry={x,y,w,h};ctx.textAlign='left';for(let i=0;i<5;i++){const value=min+(max-min)*i/4,yy=y(value);ctx.strokeStyle='#ffffff0d';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#aaa198';ctx.fillText(money(value),w-right+10,yy+4)}const gradient=ctx.createLinearGradient(0,top,0,h-bottom);gradient.addColorStop(0,'#dab66b45');gradient.addColorStop(1,'#dab66b00');ctx.beginPath();visible.forEach(([t,v],i)=>i?ctx.lineTo(x(t),y(v)):ctx.moveTo(x(t),y(v)));ctx.lineTo(x(visible.at(-1)[0]),h-bottom);ctx.lineTo(x(visible[0][0]),h-bottom);ctx.closePath();ctx.fillStyle=gradient;ctx.fill();ctx.beginPath();visible.forEach(([t,v],i)=>i?ctx.lineTo(x(t),y(v)):ctx.moveTo(x(t),y(v)));ctx.strokeStyle='#edcd85';ctx.lineWidth=2;ctx.shadowColor='#dab66b';ctx.shadowBlur=9;ctx.stroke();ctx.shadowBlur=0;for(const [t,v] of visible){ctx.beginPath();ctx.arc(x(t),y(v),3,0,Math.PI*2);ctx.fillStyle='#ffe4a4';ctx.fill()}ctx.fillStyle='#999098';ctx.textAlign='left';ctx.fillText(new Date(visible[0][0]*1000).toLocaleDateString('fr-FR'),left,h-12);ctx.textAlign='right';ctx.fillText(new Date(visible.at(-1)[0]*1000).toLocaleDateString('fr-FR'),w-right,h-12);}
 function render(){draw();updateHistoryContext(points);el('chart-data').replaceChildren();for(const [t,v] of visible){const tr=document.createElement('tr');for(const value of [date(t),money(v)]){const td=document.createElement('td');td.textContent=value;tr.append(td)}el('chart-data').append(tr)}}
 async function history(){const item=pools.find(p=>p.id===selected),ticket=++seq;if(!item)return;el('chart-status').textContent='Lecture de l’historique réel…';points=[];render();try{const url='https://api.geckoterminal.com/api/v2/networks/base/pools/'+encodeURIComponent(item.id)+'/ohlcv/hour?aggregate=1&limit=1000&currency=usd&token='+TOKEN.toLowerCase()+'&include_empty_intervals=false';const response=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error();const data=await response.json();if(ticket!==seq)return;const raw=data.data?.attributes?.ohlcv_list;if(!Array.isArray(raw))throw Error();points=raw.filter(p=>Array.isArray(p)&&typeof p[0]==='number'&&typeof p[4]==='number'&&Number.isFinite(p[4])&&p[4]>=0&&p[0]<=Date.now()/1000).map(p=>[p[0],p[4]]).sort((a,b)=>a[0]-b[0]);lastFetch=Date.now();el('chart-status').textContent=points.length?'Dernière bougie disponible : '+date(points.at(-1)[0])+'. Les points relient les clôtures disponibles ; aucun échange n’est ajouté entre eux.':'Aucune bougie retournée par cette pool. Aucun historique simulé.';render()}catch{if(ticket!==seq)return;points=[];render();el('chart-status').textContent='Historique temporairement indisponible. Nouvelle tentative à la prochaine actualisation.'}}
 document.addEventListener('mtp:pools',e=>{pools=e.detail.filter(p=>p.source==='GeckoTerminal');const old=selected;if(!pools.some(p=>p.id===selected))selected=pools[0]?.id||'';el('chart-pool').replaceChildren();for(const p of pools){const option=document.createElement('option');option.value=p.id;option.textContent=p.name+' · '+p.dex;option.selected=p.id===selected;el('chart-pool').append(option)}const current=pools.find(p=>p.id===selected);el('chart-price').textContent=current?.price!=null?money(current.price):'—';if(!current){seq++;points=[];render();el('chart-status').textContent='Pool de référence indisponible. Aucun cours affiché.';return}if(old!==selected||Date.now()-lastFetch>55000)history()});
 el('chart-pool').onchange=()=>{selected=el('chart-pool').value;const p=pools.find(p=>p.id===selected);el('chart-price').textContent=p?.price!=null?money(p.price):'—';history()};panel.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=Number(b.dataset.period);panel.querySelectorAll('[data-period]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});
 canvas.addEventListener('pointermove',e=>{if(!geometry||!visible.length)return;const px=e.clientX-canvas.getBoundingClientRect().left;const p=visible.reduce((a,b)=>Math.abs(geometry.x(a[0])-px)<Math.abs(geometry.x(b[0])-px)?a:b);el('chart-readout').textContent=date(p[0])+' · '+money(p[1])});let cursor=0;canvas.addEventListener('keydown',e=>{if(!visible.length||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();cursor=Math.max(0,Math.min(visible.length-1,cursor+(e.key==='ArrowRight'?1:-1)));el('chart-readout').textContent=date(visible[cursor][0])+' · '+money(visible[cursor][1])});new ResizeObserver(draw).observe(canvas);draw();
 setInterval(()=>{if(!document.hidden)document.getElementById('refresh-live')?.click()},60000);
}
