// Preparation only: final files, rights, seller registration and terms are pending.
const copy={
 fr:['La création fait vivre les échanges.','La BD arrive dans MTP.','2 € par tome · paiement uniquement en MTP','Découvrez les tomes disponibles et convenez du montant en MTP avant tout paiement. Contactez le créateur pour préparer votre achat.','Disponibilité sur demande. Aucun paiement n’est demandé sur cette page.','Contacter le créateur','Des annonces pour toute la communauté.','La création de comptes et la publication partagée sont en préparation. Pour le moment, vos annonces restent des brouillons sur votre appareil ; vous pouvez les partager dans la communauté.'],
 en:['Creativity brings exchange to life.','Comics are coming to MTP.','€2 per volume · payment in MTP only','Ask which volumes are available and agree on the MTP amount before paying. Contact the creator to arrange your purchase.','Availability on request. This page does not request payment.','Contact the creator','Listings for the whole community.','Accounts and shared publishing are being prepared. For now, listings remain drafts on your device; you can share them with the community.'],
 es:['La creación da vida a los intercambios.','El cómic llega a MTP.','2 € por tomo · pago solo en MTP','Consulta los tomos disponibles y acuerda el importe en MTP antes de pagar. Contacta con el creador para preparar tu compra.','Disponibilidad bajo consulta. Esta página no solicita ningún pago.','Contactar con el creador','Anuncios para toda la comunidad.','Las cuentas y la publicación compartida están en preparación. Por ahora, los anuncios son borradores en tu dispositivo; puedes compartirlos con la comunidad.'],
 it:['La creatività dà vita agli scambi.','Il fumetto arriva su MTP.','2 € a volume · pagamento solo in MTP','Chiedi quali volumi sono disponibili e concorda l’importo in MTP prima di pagare. Contatta il creatore per preparare il tuo acquisto.','Disponibilità su richiesta. Questa pagina non richiede pagamenti.','Contatta il creatore','Annunci per tutta la comunità.','Gli account e la pubblicazione condivisa sono in preparazione. Per ora gli annunci restano bozze sul tuo dispositivo; puoi condividerli con la comunità.'],
 de:['Kreativität macht Austausch lebendig.','Comics kommen zu MTP.','2 € pro Band · Zahlung ausschließlich in MTP','Frage nach verfügbaren Bänden und vereinbare den MTP-Betrag vor der Zahlung. Kontaktiere den Autor, um deinen Kauf vorzubereiten.','Verfügbarkeit auf Anfrage. Diese Seite fordert keine Zahlung an.','Autor kontaktieren','Anzeigen für die ganze Gemeinschaft.','Konten und gemeinsame Veröffentlichung werden vorbereitet. Anzeigen bleiben derzeit Entwürfe auf deinem Gerät; du kannst sie mit der Gemeinschaft teilen.'],
 ar:['الإبداع يمنح التبادل حياة.','القصص المصورة قادمة إلى MTP.','يوروَان لكل مجلد · الدفع بعملة MTP فقط','اسأل عن المجلدات المتاحة واتفق على المبلغ بعملة MTP قبل الدفع. تواصل مع المبدع لترتيب الشراء.','التوفر عند الاستفسار. هذه الصفحة لا تطلب أي دفعة.','تواصل مع المبدع','إعلانات للجميع.','الحسابات والنشر المشترك قيد التحضير. الإعلانات حالياً مسودات على جهازك؛ يمكنك مشاركتها مع المجتمع.'],
 oc:['La creacion fa viure los escambis.','La benda dessenhada arriba dins MTP.','2 € per volum · pagament sonque en MTP','Demandatz los volums disponibles e acordatz lo montant en MTP abans de pagar. Contactatz lo creator per preparar vòstra crompa.','Disponibilitat sus demanda. Aquesta pagina demanda pas cap de pagament.','Contactar lo creator','D’anóncias per tota la comunautat.','Los comptes e la publicacion partejada son en preparacion. Pel moment, las anóncias demòran d’esbòs sus vòstre aparelh ; las podètz partejar amb la comunautat.']
};
const preparation={
 fr:['Prix envisagé : 2 € par tome · règlement en MTP','Les versions corrigées des tomes I à V sont en préparation. Les droits, le statut vendeur et les conditions commerciales doivent être finalisés avant ouverture.','Aucune commande ni précommande ouverte. Aucun paiement à envoyer.','Poser une question'],
 en:['Planned price: €2 per volume · payment in MTP','Corrected final versions of volumes I–V are being prepared. Rights, seller registration and sales terms must be finalised before opening.','No orders or preorders are open. Do not send payment.','Ask a question'],
 es:['Precio previsto: 2 € por tomo · pago en MTP','Las versiones finales corregidas de los tomos I–V están en preparación. Los derechos, el registro del vendedor y las condiciones de venta deben completarse antes de la apertura.','No se aceptan pedidos ni reservas. No envíes ningún pago.','Hacer una pregunta'],
 it:['Prezzo previsto: 2 € a volume · pagamento in MTP','Le versioni definitive corrette dei volumi I–V sono in preparazione. Diritti, registrazione del venditore e condizioni di vendita devono essere definiti prima dell’apertura.','Ordini e preordini non sono aperti. Non inviare pagamenti.','Fai una domanda'],
 de:['Geplanter Preis: 2 € pro Band · Zahlung in MTP','Die korrigierten Endfassungen der Bände I–V werden vorbereitet. Rechte, Verkäuferregistrierung und Verkaufsbedingungen müssen vor dem Start geklärt werden.','Keine Bestellungen oder Vorbestellungen möglich. Bitte keine Zahlung senden.','Eine Frage stellen'],
 ar:['السعر المقترح: يوروَان لكل مجلد · الدفع بعملة MTP','النسخ النهائية المصححة للمجلدات من الأول إلى الخامس قيد التحضير. يجب استكمال الحقوق وتسجيل البائع وشروط البيع قبل الافتتاح.','الطلبات والطلبات المسبقة غير متاحة. لا ترسل أي دفعة.','اطرح سؤالاً'],
 oc:['Prètz previst : 2 € per volum · pagament en MTP','Las versions finalas corregidas dels volums I a V son en preparacion. Los dreches, l’estatut del vendeire e las condicions de venda devon èsser finalizats abans la dobertura.','Cap de comanda ni de precomanda dobèrta. Mandetz pas cap de pagament.','Pausar una question']
};
for(const [lang,t] of Object.entries(preparation))copy[lang].splice(2,4,...t);
module.exports=function({fs,path,root}){for(const [lang,t] of Object.entries(copy)){for(const route of ['','echanges']){const file=path.join(root,lang==='fr'?'':lang,route,'index.html');let html=fs.readFileSync(file,'utf8');const section=`<div class="wrap"><section class="story" id="bd"><div><div class="eyebrow">${t[0]}</div><h2>${t[1]}</h2><p class="label" dir="ltr">I · II · III · IV · V</p><p><strong>${t[2]}</strong></p><p>${t[3]}</p><a class="button" href="https://t.me/mehdisouissi">${t[5]} ↗</a><p><a class="textlink" href="https://t.me/mehdisouissi" dir="ltr">@mehdisouissi</a></p><p class="notice">${t[4]}</p></div><div><img src="/assets/logo.png" width="220" height="220" alt="Montpellier ECU" loading="lazy" style="width:220px;max-width:100%;height:auto;object-fit:contain">${route==='echanges'?`<h3>${t[6]}</h3><p>${t[7]}</p>`:''}</div></section></div>`;html=html.replace('</main>',section+'</main>');fs.writeFileSync(file,html)}}};
