const config=require('./donations.json');
module.exports=function({fs,path,root,shell,base}){
 const active=config.confirmedByUser===true&&/^0x[a-fA-F0-9]{40}$/.test(config.recipient||'')&&!/^0x0{40}$/.test(config.recipient);
 const reception=active?`<div class="contract-box"><div class="label">Portefeuille de réception · réseau Base uniquement</div><p class="contract" dir="ltr">${config.recipient}</p><div class="row"><button class="button" data-copy="${config.recipient}">Copier l’adresse</button><a class="button secondary" href="https://basescan.org/address/${config.recipient}">Voir le portefeuille ↗</a></div></div><p class="notice">Cette adresse appartient au porteur du projet. Un transfert en MTP sur Base est un soutien au projet, pas un achat ni une commande. Vérifiez le réseau et l’adresse dans votre portefeuille avant de confirmer. Les frais éventuels du réseau restent distincts du don.</p><p>Pour un don en MTP, utilisez le contrat officiel : <span class="contract" dir="ltr">0x50626097a780881d3dFf1Ff97579e6dAF965366B</span>.</p>`:`<div class="panel"><h3>Les dons seront bientôt ouverts.</h3><p>L’adresse de réception est en cours de confirmation. Aucun transfert n’est demandé pour le moment.</p><a class="button secondary" href="https://t.me/mehdisouissi">Poser une question sur Telegram ↗</a></div>`;
 let qr='';
 if(active){const code=require('qrcode').create(config.recipient,{errorCorrectionLevel:'M'}),n=code.modules.size;let pixels='';for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(code.modules.get(y,x))pixels+=`M${x+4},${y+4}h1v1h-1z`;fs.writeFileSync(path.join(root,'assets','soutenir-wallet.svg'),`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n+8} ${n+8}" shape-rendering="crispEdges"><path fill="white" d="M0 0h${n+8}v${n+8}H0z"/><path fill="black" d="${pixels}"/></svg>`);qr='<figure style="margin:24px 0"><img src="/assets/soutenir-wallet.svg" alt="QR code de l’adresse de réception du soutien MTP" width="220" height="220" style="max-width:100%;height:auto;border-radius:12px"><figcaption class="label">QR : adresse uniquement. Choisis le réseau Base dans ton portefeuille.</figcaption></figure>';}
 const content=fs.readFileSync(path.join(__dirname,'soutenir-editorial.html'),'utf8').replace('{{RECEPTION}}',reception+qr);
 const dir=path.join(root,'soutenir');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),shell('/soutenir/',{title:'Soutenir MTP — Faire beaucoup avec très peu',description:'Soutenez Montpellier ECU : philosophie Argent 0, création et outils communautaires. Contribution libre, sans promesse de rendement.',content}));
 const labels={fr:'Soutenir MTP',en:'Support MTP (FR)',es:'Apoyar MTP (FR)',it:'Sostieni MTP (FR)',de:'MTP unterstützen (FR)',ar:'دعم MTP (FR)',oc:'Sosténer MTP (FR)'};
 function visit(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())visit(file);else if(entry.name.endsWith('.html')){let html=fs.readFileSync(file,'utf8');const lang=html.match(/<html lang="([a-z]+)"/)?.[1]||'fr';html=html.replace('<div class="footer-bottom">',`<p><a class="textlink" href="/soutenir/" hreflang="fr">${labels[lang]||labels.fr} ↗</a></p><div class="footer-bottom">`);fs.writeFileSync(file,html)}}}visit(root);
 const map=path.join(root,'sitemap.xml');fs.writeFileSync(map,fs.readFileSync(map,'utf8').replace('</urlset>','<url><loc>'+base+'/soutenir/</loc></url></urlset>'));
};
