import { attachPoolDisclosure } from './pool-disclosure.js';
import { publicJson } from './market-data.js';
const TOKEN='0x50626097a780881d3dFf1Ff97579e6dAF965366B';
const words={fr:['Prix indicatif','Derniers transferts','Lecture','Indisponible','Aucun transfert retourné','Voir les transferts','Pool','Actualisation 60 s · sources : GeckoTerminal / Blockscout'],en:['Indicative price','Latest transfers','Checked','Unavailable','No transfers returned','View transfers','Pool','Refresh 60 s · sources: GeckoTerminal / Blockscout'],es:['Precio indicativo','Últimas transferencias','Consulta','No disponible','Sin transferencias','Ver transferencias','Pool','Actualización 60 s · fuentes: GeckoTerminal / Blockscout'],it:['Prezzo indicativo','Ultimi trasferimenti','Verifica','Non disponibile','Nessun trasferimento','Vedi trasferimenti','Pool','Aggiornamento 60 s · fonti: GeckoTerminal / Blockscout'],de:['Indikativer Preis','Letzte Transfers','Abgerufen','Nicht verfügbar','Keine Transfers gefunden','Transfers ansehen','Pool','Aktualisierung 60 s · Quellen: GeckoTerminal / Blockscout'],ar:['سعر استرشادي','آخر التحويلات','آخر تحقق','غير متاح','لا توجد تحويلات','عرض التحويلات','مجمع السيولة','تحديث كل 60 ثانية · المصادر: GeckoTerminal / Blockscout'],oc:['Prètz indicatiu','Darrièrs transferiments','Consultacion','Indisponible','Cap de transferiment retornat','Veire los transferiments','Pool','Actualizacion 60 s · fonts : GeckoTerminal / Blockscout']};
export function initMarketBanner(){const lang=document.documentElement.lang.split('-')[0],w=words[lang]||words.fr,locale=lang==='oc'?'fr-FR':lang;const bar=document.createElement('aside');bar.className='market-banner';bar.setAttribute('aria-label','MTP · '+w[0]+' · '+w[1]);bar.innerHTML=`<div class="market-line"><a class="market-brand" href="${lang==='fr'?'':'/'+lang}/live/">MTP <span>BASE</span></a><span class="market-quote">${w[0]} <strong id="ticker-price">—</strong></span><span class="market-time" id="ticker-time">${w[2]} : —</span><details class="market-transfers"><summary>${w[1]} <span id="ticker-last">—</span></summary><div class="market-popover"><p class="label">${w[7]}</p><ol id="ticker-transfers"><li>—</li></ol><a href="https://base.blockscout.com/token/${TOKEN}?tab=token_transfers">${w[5]} ↗</a></div></details></div>`;document.querySelector('header').after(bar);const disclosure=attachPoolDisclosure(bar,lang);let busy=false,last=0;
 async function get(url){return publicJson(url)}
 async function refresh(){if(busy)return;busy=true;last=Date.now();const results=await Promise.allSettled([get('https://api.geckoterminal.com/api/v2/networks/base/tokens/'+TOKEN+'/pools?page=1'),get('https://base.blockscout.com/api/v2/tokens/'+TOKEN+'/transfers')]);const price=document.getElementById('ticker-price'),time=document.getElementById('ticker-time'),list=document.getElementById('ticker-transfers'),latest=document.getElementById('ticker-last');price.textContent='—';price.removeAttribute('title');disclosure.clear();time.textContent=w[2]+' : '+new Date().toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'});try{if(results[0].status!=='fulfilled')throw Error();const pools=results[0].value.data;if(!Array.isArray(pools))throw Error();const token='base_'+TOKEN.toLowerCase();const p=pools.filter(p=>[p.relationships?.base_token?.data?.id?.toLowerCase(),p.relationships?.quote_token?.data?.id?.toLowerCase()].includes(token)).sort((a,b)=>Number(b.attributes?.reserve_in_usd||0)-Number(a.attributes?.reserve_in_usd||0))[0];if(!p)throw Error();const a=p.attributes,raw=p.relationships.base_token.data.id.toLowerCase()===token?a.base_token_price_usd:a.quote_token_price_usd;const n=raw==null?NaN:Number(raw);if(!Number.isFinite(n)||n<0)throw Error();price.textContent=new Intl.NumberFormat(locale,{style:'currency',currency:'USD',maximumSignificantDigits:6}).format(n);disclosure.show(p);price.title=w[6]+' : '+a.name+' · '+p.relationships.dex.data.id+' · GeckoTerminal';}catch{price.textContent=w[3]}
 list.replaceChildren();try{if(results[1].status!=='fulfilled')throw Error();const items=results[1].value.items;if(!Array.isArray(items))throw Error();const transfers=items.filter(t=>t.token?.address_hash?.toLowerCase()===TOKEN.toLowerCase()&&/^0x[a-f0-9]{64}$/i.test(t.transaction_hash)&&Number.isFinite(Date.parse(t.timestamp))).slice(0,5);latest.textContent=transfers.length?new Date(transfers[0].timestamp).toLocaleDateString(locale):w[4];for(const t of transfers){const li=document.createElement('li'),a=document.createElement('a');a.href='https://basescan.org/tx/'+t.transaction_hash;let amount='—';if(/^\d+$/.test(t.total?.value||'')){const n=BigInt(t.total.value),d=10n**18n;amount=(n/d).toLocaleString(locale)+'.'+(n%d).toString().padStart(18,'0').slice(0,4)}a.textContent=amount+' MTP · '+new Date(t.timestamp).toLocaleString(locale)+' ↗';li.append(a);list.append(li)}if(!transfers.length){const li=document.createElement('li');li.textContent=w[4];list.append(li)}}catch{latest.textContent=w[3];const li=document.createElement('li');li.textContent=w[3];list.append(li)}busy=false}
 refresh();setInterval(()=>{if(!document.hidden)refresh()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-last>=60000)refresh()});
}
