const {languages,data}=require('./locales.cjs');
const rows=`
Copié dans le presse-papiers.|Copied to clipboard.|Copiado al portapapeles.|Copiato negli appunti.|In die Zwischenablage kopiert.|تم النسخ.|Copiat dins lo quichapapièrs.
Copie impossible. Sélectionnez le texte pour le copier.|Copy failed. Select the text to copy it.|No se pudo copiar. Selecciona el texto.|Copia non riuscita. Seleziona il testo.|Kopieren fehlgeschlagen. Text auswählen.|تعذر النسخ. حدد النص لنسخه.|Còpia impossibla. Seleccionatz lo tèxte.
Réponse RPC indisponible|RPC response unavailable|Respuesta RPC no disponible|Risposta RPC non disponibile|RPC-Antwort nicht verfügbar|استجابة RPC غير متاحة|Responsa RPC indisponibla
Solde invalide|Invalid balance|Saldo no válido|Saldo non valido|Ungültiges Guthaben|رصيد غير صالح|Salde invalid
Session locale effacée. Les autorisations se gèrent dans votre portefeuille.|Local session cleared. Manage permissions in your wallet.|Sesión local borrada. Gestiona los permisos en tu cartera.|Sessione locale cancellata. Gestisci i permessi nel portafoglio.|Lokale Sitzung gelöscht. Berechtigungen in der Wallet verwalten.|مُسحت الجلسة المحلية. أدر الأذونات في محفظتك.|Session locala escafada. Gerissètz las autorizacions dins vòstre portafuèlha.
Saisissez une adresse Base valide (0x et 40 caractères hexadécimaux).|Enter a valid Base address: 0x and 40 hexadecimal characters.|Introduce una dirección Base válida: 0x y 40 caracteres hexadecimales.|Inserisci un indirizzo Base valido: 0x e 40 caratteri esadecimali.|Gültige Base-Adresse eingeben: 0x und 40 Hexadezimalzeichen.|أدخل عنوان Base صالحًا: 0x ثم 40 رمزًا سداسيًا عشريًا.|Picatz una adreça Base valida : 0x e 40 caractèrs exadecimals.
Wallet connecté · Base|Wallet connected · Base|Cartera conectada · Base|Portafoglio collegato · Base|Wallet verbunden · Base|المحفظة متصلة · Base|Portafuèlha connectat · Base
Lecture seule · Base|Read only · Base|Solo lectura · Base|Sola lettura · Base|Nur Lesen · Base|قراءة فقط · Base|Lectura sola · Base
Lecture des soldes sur Base…|Reading balances on Base…|Consultando saldos en Base…|Lettura saldi su Base…|Guthaben auf Base wird gelesen…|جارٍ قراءة الأرصدة على Base…|Lectura dels saldes sus Base…
QR indisponible. Copiez votre adresse publique.|QR unavailable. Copy your public address.|QR no disponible. Copia tu dirección pública.|QR non disponibile. Copia il tuo indirizzo pubblico.|QR nicht verfügbar. Öffentliche Adresse kopieren.|الرمز غير متاح. انسخ عنوانك العام.|QR indisponible. Copiatz vòstra adreça publica.
Certaines données sont indisponibles. Réessayez pour relire les soldes.|Some data is unavailable. Retry to refresh balances.|Algunos datos no están disponibles. Vuelve a consultar.|Alcuni dati non sono disponibili. Riprova.|Einige Daten fehlen. Guthaben erneut abrufen.|بعض البيانات غير متاحة. حاول مجددًا.|De donadas son indisponiblas. Tornatz ensajar.
Soldes lus sur Base à |Balances read on Base at |Saldos consultados en Base a las |Saldi letti su Base alle |Guthaben auf Base abgerufen um |قُرئت الأرصدة على Base في |Saldes legits sus Base a 
Connectez un portefeuille ou saisissez une adresse publique.|Connect a wallet or enter a public address.|Conecta una cartera o introduce una dirección pública.|Collega un portafoglio o inserisci un indirizzo pubblico.|Wallet verbinden oder öffentliche Adresse eingeben.|اربط محفظة أو أدخل عنوانًا عامًا.|Connectatz un portafuèlha o picatz una adreça publica.
Aucun portefeuille détecté. Ouvrez ce site dans le navigateur de votre Wallet ou utilisez une extension compatible avec Base.|No wallet detected. Use your wallet browser or a Base-compatible extension.|No se detectó una cartera. Usa su navegador o una extensión compatible con Base.|Nessun portafoglio rilevato. Usa il suo browser o un’estensione compatibile con Base.|Keine Wallet erkannt. Wallet-Browser oder Base-kompatible Erweiterung verwenden.|لم تُكتشف محفظة. استخدم متصفح محفظتك أو إضافة متوافقة مع Base.|Cap de portafuèlha detectat. Utilizatz son navegador o una extension compatibla amb Base.
Sélectionnez le réseau Base dans votre Wallet.|Select Base in your wallet.|Selecciona Base en tu cartera.|Seleziona Base nel portafoglio.|Base in deiner Wallet auswählen.|اختر شبكة Base في محفظتك.|Causissètz Base dins vòstre portafuèlha.
Aucun compte partagé.|No account shared.|Ninguna cuenta compartida.|Nessun conto condiviso.|Kein Konto geteilt.|لم تتم مشاركة حساب.|Cap de compte partejat.
Connexion annulée dans le portefeuille.|Connection cancelled in wallet.|Conexión cancelada en la cartera.|Connessione annullata nel portafoglio.|Verbindung in der Wallet abgebrochen.|أُلغي الاتصال في المحفظة.|Connexion anullada dins lo portafuèlha.
Connexion impossible.|Connection failed.|Conexión fallida.|Connessione non riuscita.|Verbindung fehlgeschlagen.|فشل الاتصال.|Connexion impossibla.
Réseau changé. Reconnectez le portefeuille sur Base.|Network changed. Reconnect on Base.|Red cambiada. Vuelve a conectar en Base.|Rete cambiata. Ricollega su Base.|Netzwerk geändert. Erneut mit Base verbinden.|تغيرت الشبكة. أعد الاتصال على Base.|Ret cambiat. Tornatz connectar sus Base.
Interrogation des sources…|Checking sources…|Consultando fuentes…|Consultazione fonti…|Quellen werden abgefragt…|جارٍ التحقق من المصادر…|Consultacion de las fonts…
 : indisponible|: unavailable|: no disponible|: non disponibile|: nicht verfügbar|: غير متاح| : indisponible
 : réponse invalide|: invalid response|: respuesta no válida|: risposta non valida|: ungültige Antwort|: استجابة غير صالحة| : responsa invalida
 pool(s) retournée(s)| pool(s) returned| pool(s) encontradas| pool restituite| Pools gefunden| مجمعات معروضة| pool(s) retornada(s)
Plateforme inconnue|Unknown platform|Plataforma desconocida|Piattaforma sconosciuta|Unbekannte Plattform|منصة غير معروفة|Plataforma desconeguda
Aucune pool MTP retournée par les sources disponibles. Cela ne prouve pas l’absence du token sur Base.|No MTP pool returned. This does not prove the token is absent from Base.|No se encontró una pool MTP. Esto no prueba que el token no exista en Base.|Nessuna pool MTP restituita. Non prova l’assenza del token su Base.|Kein MTP-Pool gefunden. Das beweist nicht, dass der Token auf Base fehlt.|لم يُعرض مجمع MTP. هذا لا يثبت غياب الرمز عن Base.|Cap de pool MTP retornada. Aquò pròva pas l’abséncia del token sus Base.
Sources momentanément indisponibles. Réessayez dans quelques instants.|Sources temporarily unavailable. Try again shortly.|Fuentes temporalmente no disponibles. Reintenta pronto.|Fonti temporaneamente non disponibili. Riprova tra poco.|Quellen vorübergehend nicht verfügbar. Bald erneut versuchen.|المصادر غير متاحة مؤقتًا. حاول بعد قليل.|Fonts temporàriament indisponiblas. Tornatz ensajar lèu.
Sources consultées|Sources checked|Fuentes consultadas|Fonti consultate|Quellen abgerufen|تم التحقق من المصادر|Fonts consultadas
Échec de consultation|Source check failed|Consulta fallida|Consultazione non riuscita|Abruf fehlgeschlagen|فشل التحقق|Fracàs de consultacion
 à | at | a las | alle | um | في | a 
 · actualisation automatique · 60 s| · automatic refresh · 60 s| · actualización automática · 60 s| · aggiornamento automatico · 60 s| · automatische Aktualisierung · 60 s| · تحديث تلقائي · 60 ثانية| · actualizacion automatica · 60 s
. GeckoTerminal : première page (20 pools maximum). Doublons regroupés par identifiant de pool ; GeckoTerminal prioritaire. Totaux non affichés si une valeur manque.|. GeckoTerminal: first page (up to 20 pools). Duplicates grouped by pool ID; GeckoTerminal takes priority. Totals hidden if a value is missing.|. GeckoTerminal: primera página (hasta 20 pools). Duplicados agrupados por ID; prioridad GeckoTerminal. Sin totales si falta un valor.|. GeckoTerminal: prima pagina (massimo 20 pool). Duplicati raggruppati per ID; priorità GeckoTerminal. Totali nascosti se manca un valore.|. GeckoTerminal: erste Seite (bis 20 Pools). Duplikate nach Pool-ID gruppiert; GeckoTerminal hat Vorrang. Keine Summe bei fehlenden Werten.|. GeckoTerminal: الصفحة الأولى (حتى 20 مجمعًا). تُدمج التكرارات حسب معرف المجمع مع أولوية GeckoTerminal. لا تظهر المجاميع إذا نقصت قيمة.|. GeckoTerminal : primièra pagina (20 pools maximum). Dobles recampats per identificant ; prioritat GeckoTerminal. Pas de totals se manca una valor.
Aucun brouillon pour le moment. Votre prochaine idée commence au-dessus.|No drafts yet. Create your first one above.|Aún no hay borradores. Crea el primero arriba.|Nessuna bozza. Crea la prima qui sopra.|Noch keine Entwürfe. Erstelle oben den ersten.|لا توجد مسودات بعد. أنشئ الأولى أعلاه.|Cap de borrolhon encara. Creatz lo primièr çai dessús.
Montant à convenir|Amount to be agreed|Importe a convenir|Importo da concordare|Betrag nach Vereinbarung|المبلغ بالاتفاق|Montant de convéner
Copier pour partager|Copy to share|Copiar para compartir|Copia per condividere|Zum Teilen kopieren|نسخ للمشاركة|Copiar per partejar
Supprimer|Delete|Eliminar|Elimina|Löschen|حذف|Suprimir
Stockage indisponible. Suppression non enregistrée.|Storage unavailable. Deletion not saved.|Almacenamiento no disponible. No se guardó la eliminación.|Archiviazione non disponibile. Eliminazione non salvata.|Speicher nicht verfügbar. Löschung nicht gespeichert.|التخزين غير متاح. لم يُحفظ الحذف.|Estocatge indisponible. Supression pas enregistrada.
Stockage indisponible. Votre brouillon n’a pas été enregistré.|Storage unavailable. Draft not saved.|Almacenamiento no disponible. Borrador no guardado.|Archiviazione non disponibile. Bozza non salvata.|Speicher nicht verfügbar. Entwurf nicht gespeichert.|التخزين غير متاح. لم تُحفظ المسودة.|Estocatge indisponible. Borrolhon pas enregistrat.
Brouillon enregistré sur cet appareil. Il n’est pas publié.|Draft saved on this device. It is not published.|Borrador guardado en este dispositivo. No está publicado.|Bozza salvata su questo dispositivo. Non è pubblicata.|Entwurf auf diesem Gerät gespeichert. Nicht veröffentlicht.|حُفظت المسودة على هذا الجهاز ولم تُنشر.|Borrolhon enregistrat sus aqueste aparelh. Es pas publicat.
Prix indicatif de la pool sélectionnée|Indicative price of selected pool|Precio indicativo de la pool seleccionada|Prezzo indicativo della pool selezionata|Indikativer Preis des gewählten Pools|السعر الاسترشادي للمجمع المحدد|Prètz indicatiu de la pool causida
Pool de référence|Reference pool|Pool de referencia|Pool di riferimento|Referenzpool|المجمع المرجعي|Pool de referéncia
Chargement…|Loading…|Cargando…|Caricamento…|Laden…|جارٍ التحميل…|Cargament…
Période du graphique|Chart period|Periodo del gráfico|Periodo del grafico|Diagrammzeitraum|فترة الرسم|Periòde del grafic
7 jours|7 days|7 días|7 giorni|7 Tage|7 أيام|7 jorns
Historique|History|Historial|Storico|Verlauf|السجل|Istoric
Survolez ou touchez la courbe pour lire un cours.|Hover or touch the chart to read a price.|Pasa el cursor o toca el gráfico para leer un precio.|Passa il mouse o tocca il grafico per leggere un prezzo.|Mit Maus oder Berührung einen Kurs ablesen.|مرر المؤشر أو المس الرسم لقراءة السعر.|Passatz lo cursor o tocatz lo grafic per legir un prètz.
Historique du prix MTP en dollars. Les valeurs sont aussi disponibles dans le tableau ci-dessous.|MTP price history in dollars. Values are also in the table below.|Historial MTP en dólares. Valores también en la tabla inferior.|Storico MTP in dollari. Valori anche nella tabella sotto.|MTP-Kursverlauf in Dollar. Werte auch in der Tabelle unten.|سجل سعر MTP بالدولار. القيم متاحة في الجدول أدناه.|Istoric del prètz MTP en dòlars. Valors tanben dins lo tablèu çai jos.
En attente des pools…|Waiting for pools…|Esperando pools…|In attesa delle pool…|Warten auf Pools…|بانتظار المجمعات…|En espèra de las pools…
GeckoTerminal · clôtures horaires · USD|GeckoTerminal · hourly closes · USD|GeckoTerminal · cierres horarios · USD|GeckoTerminal · chiusure orarie · USD|GeckoTerminal · stündliche Schlusskurse · USD|GeckoTerminal · إغلاقات كل ساعة · USD|GeckoTerminal · clausuras oràrias · USD
Actualisation automatique · 60 s|Automatic refresh · 60 s|Actualización automática · 60 s|Aggiornamento automatico · 60 s|Automatische Aktualisierung · 60 s|تحديث تلقائي · 60 ثانية|Actualizacion automatica · 60 s
Consulter les valeurs du graphique|View chart values|Ver valores del gráfico|Vedi valori del grafico|Diagrammwerte ansehen|عرض قيم الرسم|Consultar las valors del grafic
Clôture MTP / USD|MTP / USD close|Cierre MTP / USD|Chiusura MTP / USD|MTP / USD Schlusskurs|إغلاق MTP / USD|Clausura MTP / USD
Aucun échange disponible sur cette période.|No trades available for this period.|Sin operaciones en este periodo.|Nessuno scambio in questo periodo.|Keine Trades in diesem Zeitraum.|لا توجد تداولات لهذه الفترة.|Cap d’escambi disponible sus aqueste periòde.
Lecture de l’historique réel…|Loading actual history…|Cargando historial real…|Caricamento storico reale…|Tatsächlicher Verlauf wird geladen…|جارٍ تحميل السجل الفعلي…|Lectura de l’istoric real…
Dernière bougie disponible : |Latest available candle: |Última vela disponible: |Ultima candela disponibile: |Letzte verfügbare Kerze: |آخر شمعة متاحة: |Darrièra candèla disponibla : 
. Les points relient les clôtures disponibles ; aucun échange n’est ajouté entre eux.|. Points connect available closes; no trades are added between them.|. Los puntos unen cierres disponibles; no se añaden operaciones entre ellos.|. I punti collegano chiusure disponibili; nessuno scambio viene aggiunto.|. Punkte verbinden verfügbare Schlusskurse; keine Trades werden ergänzt.|. تصل النقاط بين الإغلاقات المتاحة ولا تُضاف تداولات بينها.|. Los punts ligan las clausuras disponiblas ; cap d’escambi es pas apondut entre eles.
Aucune bougie retournée par cette pool. Aucun historique simulé.|No candles returned by this pool. No simulated history.|Sin velas para esta pool. No se simula historial.|Nessuna candela per questa pool. Nessuno storico simulato.|Keine Kerzen für diesen Pool. Kein simulierter Verlauf.|لم يُرجع هذا المجمع شموعًا. لا يوجد سجل محاكى.|Cap de candèla retornada per aquesta pool. Cap d’istoric simulat.
Historique temporairement indisponible. Nouvelle tentative à la prochaine actualisation.|History temporarily unavailable. Retrying at next refresh.|Historial no disponible temporalmente. Reintento en la próxima actualización.|Storico temporaneamente non disponibile. Nuovo tentativo al prossimo aggiornamento.|Verlauf vorübergehend nicht verfügbar. Neuer Versuch bei Aktualisierung.|السجل غير متاح مؤقتًا. إعادة المحاولة عند التحديث القادم.|Istoric temporàriament indisponible. Ensag novèl a l’actualizacion venenta.
Pool de référence indisponible. Aucun cours affiché.|Reference pool unavailable. No price displayed.|Pool de referencia no disponible. Sin precio.|Pool di riferimento non disponibile. Nessun prezzo.|Referenzpool nicht verfügbar. Kein Preis angezeigt.|المجمع المرجعي غير متاح. لا يُعرض سعر.|Pool de referéncia indisponibla. Cap de prètz afichat.
`;
const maps=Object.fromEntries(languages.map(l=>[l,{}]));for(const line of rows.trim().split('\n')){const [fr,...v]=line.split('|');if(v.length!==6)throw Error('Runtime translation '+fr);languages.forEach((l,i)=>maps[l][fr]=v[i]);}
for(const lang of languages){const t=data[lang];Object.assign(maps[lang],{'Non connecté':t.disconnected,'Date':{en:'Date',es:'Fecha',it:'Data',de:'Datum',ar:'التاريخ',oc:'Data'}[lang]});}
module.exports=maps;
