const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/msoui/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.join(__dirname,'site'),report={date:new Date().toISOString(),checks:[],errors:[]},ok=s=>{report.checks.push(s);console.log('PASS '+s)};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local'),file=path.join(root,url.pathname,url.pathname.endsWith('/')?'index.html':'');try{res.setHeader('content-type',({'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end()}});
(async()=>{
const config=require('./legal-readiness.json');assert.equal(config.seller.siret,null);assert.equal(config.books.salesEnabled,false);assert.equal(config.tokenSale.salesEnabled,false);assert.equal(config.marketplace.salesEnabled,false);assert.equal(require('../audit/lancement-bd/catalogue.json').salesEnabled,false);assert.equal(require('../vente-directe-MTP/offre.json').saleEnabled,false);ok('Trois activités fermées ; aucun statut ou SIRET inventé');
const xml=fs.readFileSync('site/sitemap.xml','utf8'),urls=[...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]);assert.equal(urls.length,45);assert.equal(new Set(urls).size,45);assert.equal((xml.match(/<xhtml:link /g)||[]).length,42*8);for(const url of urls){const html=fs.readFileSync(path.join(root,new URL(url).pathname,'index.html'),'utf8');assert(html.includes('href="/informations/"'));assert(!html.includes('wpesig='));assert(!html.includes('Découvrez les tomes disponibles'));assert(!html.includes('Availability on request'));}ok('45 pages liées aux informations ; sitemap alternates ; aucun lien privé Maïa');
await new Promise(r=>server.listen(19364,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
await page.route('https://api.geckoterminal.com/**',r=>r.fulfill({json:r.request().url().includes('/ohlcv/')?JSON.parse(fs.readFileSync('verification/ohlcv-real.json','utf8').replace(/^\uFEFF/,'')):JSON.parse(fs.readFileSync('../audit/gecko-pools.txt','utf8').replace(/^\uFEFF/,''))}));await page.route('https://api.dexscreener.com/**',r=>r.fulfill({json:[]}));await page.route('https://base.blockscout.com/**',r=>r.fulfill({json:{items:[]}}));
for(const route of ['/informations/','/soutenir/','/charte/','/ar/echanges/']){await page.goto('http://127.0.0.1:19364'+route);assert.equal(await page.locator('h1').count(),1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route);await page.screenshot({path:'verification/audit-'+route.replaceAll('/','-')+'.png',fullPage:true});}ok('Nouvelles informations, soutien, charte et échanges AR : mobile sans débordement');
await page.goto('http://127.0.0.1:19364/live/');await page.waitForFunction(()=>document.querySelector('#chart-data').children.length>0);assert.equal(await page.locator('#chart-freshness').isVisible(),true);await page.locator('[data-period="1"]').click();assert.equal(await page.locator('#chart-data tr').count(),0);assert(!(await page.locator('#chart-readout').textContent()).includes('$'));ok('Historique ancien signalé ; période sans échange reste vide');
await page.evaluate(()=>document.dispatchEvent(new CustomEvent('mtp:pools',{detail:[{id:'0x'+'1'.repeat(40),name:'=HYPERLINK("bad")',dex:'test',price:0.1,liquidity:2,volume:0,source:'test',url:'https://example.invalid'}]})));assert((await page.locator('#live-quality').textContent()).includes('très faibles'));const downloadPromise=page.waitForEvent('download');await page.locator('#export-pools').click();const download=await downloadPromise,csv=fs.readFileSync(await download.path(),'utf8');assert(csv.includes('checked_at_utc'));assert(csv.includes("'=HYPERLINK"));assert(csv.includes('"2","0"'));ok('Export CSV daté, vrais zéros et neutralisation des formules');
await page.evaluate(()=>document.dispatchEvent(new CustomEvent('mtp:pools',{detail:[]})));assert(await page.locator('#export-pools').isDisabled());assert.equal(await page.locator('#chart-price').textContent(),'—');ok('Données absentes : export fermé et cours effacé');assert.deepEqual(report.errors,[]);
}finally{await browser.close();server.close();fs.writeFileSync('verification/audit-tests.json',JSON.stringify(report,null,2))}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
