const {chromium}=require('C:/Users/msoui/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'site'),out=path.join(__dirname,'verification');fs.mkdirSync(out,{recursive:true});
const types={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.png':'image/png','.xml':'application/xml','.txt':'text/plain'};
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let file=path.join(root,decodeURIComponent(u.pathname));if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403);return res.end()}try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('content-type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end('404')}});
const report={checks:[],errors:[]};const ok=s=>{report.checks.push(s);console.log('PASS '+s)};
(async()=>{await new Promise(r=>server.listen(19358,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.errors.push(e.message));
 await page.route('https://api.geckoterminal.com/**',route=>route.fulfill({json:JSON.parse(fs.readFileSync(path.join(__dirname,'../audit/gecko-pools.txt'),'utf8').replace(/^\uFEFF/,''))}));await page.route('https://api.dexscreener.com/**',route=>route.fulfill({json:[]}));
 await page.route('https://mainnet.base.org/**',async route=>{const q=route.request().postDataJSON();await route.fulfill({json:{jsonrpc:'2.0',id:q.id,result:q.method==='eth_call'?'0x'+(123456789012345678901n).toString(16):'0x'+(2n*10n**18n).toString(16)}})});
 for(const url of ['/','/wallet/','/live/','/echanges/','/confidentialite/']){await page.goto('http://127.0.0.1:19358'+url);await page.waitForTimeout(300);assert(await page.locator('h1').count()===1);const broken=await page.locator('img').evaluateAll(async imgs=>{await Promise.all(imgs.map(i=>{i.loading='eager';return i.decode().catch(()=>{})}));return imgs.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)});assert.deepEqual(broken,[]);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,(url==='/'?'accueil':url.split('/')[1])+'-desktop.png'),fullPage:true});ok(url+' : titre, images, largeur ordinateur');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,(url==='/'?'accueil':url.split('/')[1])+'-mobile.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));ok(url+' : largeur mobile');await page.setViewportSize({width:1440,height:1000});}
 await page.goto('http://127.0.0.1:19358/wallet/');await page.locator('#address').fill('0x320f6C7aaD64f6DAf91A853aAA5ceaE6fa740626');await page.locator('#watch-form button').click();await page.waitForFunction(()=>document.querySelector('#mtp-balance').textContent.includes('123'));assert.equal(await page.locator('#mtp-balance').textContent(),'123,456789012345678901');assert.equal(await page.locator('#eth-balance').textContent(),'2');await page.locator('#receive-qr').waitFor({state:'visible'});ok('Wallet : précision 18 décimales, solde ETH, QR code');await page.reload();await page.waitForFunction(()=>document.querySelector('#mtp-balance').textContent.includes('123'));ok('Wallet : restauration adresse en lecture seule');await page.locator('#disconnect').click();assert.equal(await page.locator('#mtp-balance').textContent(),'—');assert.equal(await page.evaluate(()=>localStorage.getItem('mtp.web.address')),null);ok('Wallet : effacement local');
 await page.unroute('https://mainnet.base.org/**');await page.route('https://mainnet.base.org/**',r=>r.fulfill({status:503,body:'Unavailable'}));await page.locator('#address').fill('0x320f6C7aaD64f6DAf91A853aAA5ceaE6fa740626');await page.locator('#watch-form button').click();await page.waitForFunction(()=>document.querySelector('#wallet-status').textContent.includes('indisponibles'));assert.equal(await page.locator('#mtp-balance').textContent(),'—');ok('Wallet : échec réseau sans faux solde');
 await page.goto('http://127.0.0.1:19358/live/');await page.waitForFunction(()=>document.querySelector('#pool-count').textContent!=='—');assert(Number(await page.locator('#pool-count').textContent())>0);assert((await page.locator('#source-details').textContent()).includes('DexScreener : 0'));ok('Live : pools GeckoTerminal malgré DexScreener vide');await page.unroute('https://api.geckoterminal.com/**');await page.route('https://api.geckoterminal.com/**',r=>r.fulfill({json:{data:[]}}));await page.locator('#refresh-live').click();await page.waitForFunction(()=>document.querySelector('#pool-count').textContent==='0');assert.equal(await page.locator('#pool-liquidity').textContent(),'—');ok('Live : sources vides sans prix inventé');await page.unroute('https://api.geckoterminal.com/**');await page.unroute('https://api.dexscreener.com/**');await page.route('https://api.geckoterminal.com/**',r=>r.abort());await page.route('https://api.dexscreener.com/**',r=>r.abort());await page.locator('#refresh-live').click();await page.waitForFunction(()=>document.querySelector('#live-status').textContent.includes('Échec'));assert.equal(await page.locator('#pool-count').textContent(),'—');ok('Live : panne de toutes les sources');
 await page.goto('http://127.0.0.1:19358/echanges/');await page.locator('#listing-title').fill('<img src=x onerror=alert(1)>');await page.locator('#listing-description').fill('Un objet de test');await page.locator('#listing-form button').click();assert.equal(await page.locator('#listings img').count(),0);await page.reload();assert.equal(await page.locator('#listings h3').textContent(),'<img src=x onerror=alert(1)>');await page.getByRole('button',{name:'Supprimer',exact:true}).click();assert.equal(await page.locator('#listings h3').count(),0);ok('Échanges : persistance, suppression, texte HTML inerte');
 await page.goto('http://127.0.0.1:19358/');const links=await page.locator('a[href^="/"]').evaluateAll(a=>[...new Set(a.map(x=>x.getAttribute('href').split('#')[0]||'/'))]);for(const l of links)assert.equal((await page.request.get('http://127.0.0.1:19358'+l)).status(),200);const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.equal(html.split('dd5Q-tNJBukcYTLHoUMFdbqoDc57R21S3035zFzvjMk').length-1,1);ok('Liens internes et balise Google exacte présente une fois');assert.deepEqual(report.errors,[]);ok('Aucune erreur JavaScript');
 }finally{await browser.close();server.close();fs.writeFileSync(path.join(out,'tests.json'),JSON.stringify(report,null,2))}})().catch(e=>{console.error(e);server.close();process.exitCode=1});

