const {data,esc,routes,library,asset,contents,appendix}=require('./engineering-render.cjs');
module.exports=({fs,path,root,shell})=>{
 const archives=JSON.parse(fs.readFileSync(path.join(__dirname,'static/assets/ia-archives/manifest.json'),'utf8')).documents;
 const repo='https://github.com/jedi566666/MontpellierECU';
 const write=(route,html,lang)=>{html=html.replace('</head>','<link rel="stylesheet" href="/engineering.css"></head>');if(lang==='en')html=html.replace('lang="fr"','lang="en"').replace('content="fr_FR"','content="en_US"').replace('"inLanguage":"fr-FR"','"inLanguage":"en"').replace('src="/app.js"','src="/app-en.js"').replaceAll('Aller au contenu','Skip to content').replaceAll('Navigation principale','Main navigation').replaceAll('La communauté','Community').replaceAll('Liens utiles','Useful links').replaceAll('Découvrir','Discover').replaceAll('Échanges','Marketplace').replaceAll('Le projet','The project').replaceAll('Transparence','Transparency').replaceAll('Communauté','Community').replaceAll('Confidentialité & données','Privacy & data').replaceAll('Racines occitanes. Horizon ouvert.','Occitan roots. Open horizons.').replaceAll('Merci OpenAI · Tutoriels','Thank you OpenAI · Tutorials');fs.mkdirSync(path.join(root,route),{recursive:true});fs.writeFileSync(path.join(root,route,'index.html'),html);};
 fs.copyFileSync(path.join(__dirname,'engineering.css'),path.join(root,'engineering.css'));
 for(const lang of ['fr','en']){
  const fr=lang==='fr',other=fr?'en':'fr';
  const switches=(set)=>`<link rel="alternate" hreflang="fr" href="https://mtptoken.pages.dev${set.fr}"><link rel="alternate" hreflang="en" href="https://mtptoken.pages.dev${set.en}">`;
  const content=`<article class="wrap eng-page"><nav class="eng-breadcrumb"><a href="/ia/">${fr?'Atelier IA':'AI workshop'}</a> / ${fr?'Dossier technique':'Engineering dossier'}</nav><header class="eng-hero"><div class="eng-kicker">ÉDITION / EDITION 2026 · FR / EN</div><h1>${esc(data.title[lang])}</h1><p class="lede">${esc(data.subtitle[lang])}</p><div class="eng-stats"><span>18 ${fr?'chapitres':'chapters'}</span><span>6 ${fr?'captures réelles':'real screenshots'}</span><span>2 ${fr?'annexes techniques':'technical appendices'}</span></div><div class="actions"><a class="button" href="${asset}${lang}.pdf">PDF ${lang.toUpperCase()} ↓</a><a class="button secondary" lang="${other}" href="${routes[other]}">${fr?'Read in English':'Lire en français'}</a><a class="button secondary" href="${library[lang]}">${fr?'Les archives PDF':'PDF archives'} →</a></div><p class="eng-note">${fr?'État documenté au 30 septembre 2026. V1 validée; développements ultérieurs séparés.':'Documented as of 30 September 2026. V1 approved; subsequent development kept separate.'}</p></header><nav class="eng-toc" aria-label="${fr?'Sommaire':'Contents'}"><h2>${fr?'Dans le dossier':'Inside the dossier'}</h2><ol>${data.chapters.map((c,i)=>`<li><a href="#chapter-${i+1}">${esc(c.title[lang].slice(5))}</a></li>`).join('')}<li><a href="#routes">${fr?'Routes des modèles':'Model routes'}</a></li><li><a href="#references">${fr?'Sources et limites':'Sources and limitations'}</a></li></ol></nav>${contents(lang)}${appendix(lang)}<footer class="eng-end"><a href="${repo}/blob/main/docs/ENGINEERING-${lang.toUpperCase()}.md">${fr?'Lire la source Markdown sur GitHub':'Read the Markdown source on GitHub'} ↗</a></footer></article>`;
  write(routes[lang],shell(routes[lang],{title:esc(data.title[lang])+' · MTP',description:esc(data.subtitle[lang]),content}).replace('</head>',switches(routes)+'</head>'),lang);
  const cards=archives.map(a=>`<article class="eng-archive"><div class="eng-kicker">ARCHIVE ${String(a.id).padStart(2,'0')} · ${a.language.toUpperCase()}</div><h2>${esc(a.title[lang])}</h2><p>${a.pages} pages · ${(a.bytes/1048576).toFixed(1)} Mo / MB${a.redacted?' · '+(fr?'Copie expurgée':'Redacted copy'):''}</p><p class="eng-filename">${esc(a.original_name)}</p>${a.id===2?`<p>${fr?'Catalogue de ressources Godot. Ce titre ne prouve pas une livraison Bêta 3.':'Godot resource catalogue. This title does not prove a Beta 3 release.'}</p>`:''}${a.redacted?`<p>${fr?'Valeur d’authentification ou identifiants de compte masqués. Original local conservé.':'Authentication value or account identifiers masked. Local original preserved.'}</p>`:''}<div class="actions"><a class="button secondary" href="/assets/ia-archives/${a.file}">PDF ↓</a><a class="textlink" href="${repo}/blob/main/website/portal/static/assets/ia-archives/${a.file}">GitHub ↗</a></div><details><summary>SHA-256</summary><code class="eng-hash">${a.sha256}</code></details></article>`).join('');
  const old=[['/assets/matrix-pro/fr.pdf','MATRIX Pro · FR'],['/assets/matrix-pro/en.pdf','MATRIX Pro · EN'],['/assets/behind-scenes/fr.pdf','Coulisses / Behind the scenes · FR'],['/assets/behind-scenes/en.pdf','Coulisses / Behind the scenes · EN']];
  const libContent=`<div class="wrap eng-page"><nav class="eng-breadcrumb"><a href="/ia/">${fr?'Atelier IA':'AI workshop'}</a> / Archives</nav><header class="eng-hero"><div class="eng-kicker">BIBLIOTHÈQUE / LIBRARY · 30.09.2026</div><h1>${fr?'La mémoire de l’atelier.':'The workshop archive.'}</h1><p class="lede">${fr?'Neuf archives, 111 pages : les essais, les pannes, les idées et la construction de MATRIX. Avec le nouveau dossier technique et les guides déjà publiés.':'Nine archives, 111 pages: experiments, failures, ideas and the construction of MATRIX. Alongside the new engineering dossier and previously published guides.'}</p><div class="actions"><a class="button" href="${routes[lang]}">${fr?'Dossier technique illustré':'Illustrated engineering dossier'} →</a><a class="button secondary" href="${library[other]}" lang="${other}">${fr?'English library':'Bibliothèque française'}</a></div><p class="eng-note">${fr?'Documents historiques : leurs chiffres, autorisations et configurations peuvent avoir changé. Les archives originales sont majoritairement en français; le nouveau dossier est intégralement disponible en FR et EN.':'Historical documents: figures, authorizations and configurations may have changed. Original archives are mainly in French; the new dossier is fully available in French and English.'}</p></header><section class="eng-chapter"><h2>${fr?'Les éditions techniques actuelles':'Current technical editions'}</h2><div class="actions"><a class="button" href="${asset}fr.pdf">Nouveau dossier · PDF FR ↓</a><a class="button" href="${asset}en.pdf">New dossier · PDF EN ↓</a></div><p>${fr?'Guides précédents, conservés dans leur édition d’origine :':'Previous guides, preserved in their original edition:'}</p><ul>${old.map(([url,label])=>`<li><a href="${url}">${label} · PDF ↓</a></li>`).join('')}</ul></section><div class="eng-archive-grid">${cards}</div><section class="eng-chapter"><h2>${fr?'Vérifier et replacer dans le temps':'Verify and understand the chronology'}</h2><p>${fr?'Le manifeste distingue l’empreinte originale et celle de la copie publiée. Les masquages sont définitifs dans les PDF publics. Le catalogue BETA 3 ne prouve aucune extension installée; Archives Deluxe contient des chiffres historiques de ville et de MTP, qui ne remplacent pas les registres actuels.':'The manifest distinguishes original hashes from published-copy hashes. Redactions permanently remove the masked content from public PDFs. The BETA 3 catalogue proves no installed extension; Archives Deluxe contains historical city and MTP figures that do not replace current registries.'}</p><p><a href="/assets/ia-archives/manifest.json">${fr?'Manifeste des archives':'Archive manifest'} · JSON</a> · <a href="${repo}/blob/main/docs/IA-ARCHIVES.md">${fr?'Index GitHub':'GitHub index'} ↗</a></p></section></div>`;
  write(library[lang],shell(library[lang],{title:fr?'Archives IA · MATRIX & Frankenstein · MTP':'AI archives · MATRIX & Frankenstein · MTP',description:fr?'Neuf PDF historiques, 111 pages et un nouveau dossier technique bilingue illustré.':'Nine historical PDFs, 111 pages and a new illustrated bilingual engineering dossier.',content:libContent}).replace('</head>',switches(library)+'</head>'),lang);
  let md=`# ${data.title[lang]}\n\n${data.subtitle[lang]}\n\n2026-09-30 · Mehdi Souissi / Codex\n\n[Web](https://mtptoken.pages.dev${routes[lang]}) · [PDF](https://mtptoken.pages.dev${asset}${lang}.pdf) · [Archives](https://mtptoken.pages.dev${library[lang]})\n\n`;
  md+=data.chapters.map(c=>`## ${c.title[lang]}\n\n${c.paragraphs.map(p=>p[lang]).join('\n\n')}${c.code?'\n\n```text\n'+c.code+'\n```':''}${c.image?`\n\n![${c.caption[lang]}](../website/portal/static/assets/engineering/${c.image})\n\n*${c.caption[lang]}*`:''}`).join('\n\n');
  md+='\n\n## References / Références\n\n'+data.references.map(([id,label,url])=>`- [${id} — ${label}](${url})`).join('\n')+'\n\n[Model routes / Routes des modèles](../website/portal/static/assets/engineering/model-routes.json) · [Source hashes / Empreintes](../website/portal/static/assets/engineering/source-snapshot.json)\n';
  fs.writeFileSync(path.join(__dirname,'../../docs',`ENGINEERING-${lang.toUpperCase()}.md`),md);
 }
 for(const route of ['/ia/','/documentation/','/frankenstein/']){const p=path.join(root,route,'index.html');let html=fs.readFileSync(p,'utf8');html=html.replace('<main id="main">','<main id="main"><aside class="wrap eng-entry"><span class="eyebrow">Nouveau · 30 septembre 2026</span><h2>Jeu Godot, MATRIX et AWS : dans les rouages.</h2><p>18 chapitres techniques FR / EN, captures réelles encadrées d’or, deux PDF et neuf archives historiques.</p><div class="actions"><a class="button" href="/ia/technique/">Lire le dossier →</a><a class="button secondary" href="/en/ai/engineering/" lang="en">English edition</a><a class="button secondary" href="/ia/archives/">Tous les PDF ↓</a></div></aside>').replace('</head>','<link rel="stylesheet" href="/engineering.css"></head>');fs.writeFileSync(p,html);}
 let index='# Archives IA / AI archives\n\n[Bibliothèque FR](https://mtptoken.pages.dev/ia/archives/) · [English library](https://mtptoken.pages.dev/en/ai/archives/)\n\nNeuf archives historiques / Nine historical archives. 111 pages. Les documents restent datés; ils ne certifient pas la version courante. Historical documents do not certify the current implementation.\n\n';
 index+=archives.map(a=>`- [${a.title.fr}](../website/portal/static/assets/ia-archives/${a.file}) — ${a.pages} pages${a.redacted?' — copie expurgée / redacted copy':''}`).join('\n');
 index+='\n\n## Nouveau dossier / New dossier\n\n- [Technique FR](ENGINEERING-FR.md) · [PDF FR](../website/portal/static/assets/engineering/fr.pdf)\n- [Engineering EN](ENGINEERING-EN.md) · [PDF EN](../website/portal/static/assets/engineering/en.pdf)\n\n## Guides antérieurs / Earlier guides\n\n- [MATRIX FR](../website/portal/static/assets/matrix-pro/fr.pdf) · [MATRIX EN](../website/portal/static/assets/matrix-pro/en.pdf)\n- [Coulisses FR](../website/portal/static/assets/behind-scenes/fr.pdf) · [Behind the scenes EN](../website/portal/static/assets/behind-scenes/en.pdf)\n\n[Manifeste / Manifest](../website/portal/static/assets/ia-archives/manifest.json): original names, public filenames, page counts, original and public SHA-256, redaction notes. Local originals preserved.\n';
 fs.writeFileSync(path.join(__dirname,'../../docs/IA-ARCHIVES.md'),index);
 console.log('Built engineering FR/EN and archive library FR/EN');
};
