// Each row: key | English | Spanish | Italian | German | Arabic | Occitan.
const rows=`
discover|Discover|Descubrir|Scopri|Entdecken|اكتشف|Descobrir
wallet|Wallet|Cartera|Portafoglio|Wallet|المحفظة|Portafuèlha
live|Live|Live|Live|Live|مباشر|Live
exchange|Exchanges|Intercambios|Scambi|Austausch|التبادلات|Escambis
community|Community|Comunidad|Comunità|Gemeinschaft|المجتمع|Comunautat
docs|Documentation|Documentación|Documentazione|Dokumentation|التوثيق|Documentacion
privacy|Privacy & data|Privacidad y datos|Privacy e dati|Datenschutz|الخصوصية والبيانات|Confidencialitat e donadas
skip|Skip to content|Saltar al contenido|Vai al contenuto|Zum Inhalt|انتقل إلى المحتوى|Anar al contengut
nav|Main navigation|Navegación principal|Navigazione principale|Hauptnavigation|التنقل الرئيسي|Navigacion principala
links|Useful links|Enlaces útiles|Link utili|Nützliche Links|روابط مفيدة|Ligams utils
project|The project|El proyecto|Il progetto|Das Projekt|المشروع|Lo projècte
transparency|Transparency|Transparencia|Trasparenza|Transparenz|الشفافية|Transparéncia
identity|Born in Montpellier. Open to the world.|Nacido en Montpellier. Abierto al mundo.|Nato a Montpellier. Aperto al mondo.|In Montpellier entstanden. Offen für die Welt.|من مونبلييه إلى العالم.|Nascut a Montpelhièr. Dobèrt sul mond.
hero1|Another idea|Otra idea|Un’altra idea|Eine andere Idee|فكرة أخرى|Una autra idèa
hero2|of value.|del valor.|di valore.|von Wert.|عن القيمة.|de la valor.
intro|People, exchanges and local roots. Explore Montpellier ECU, a community project on Base.|Personas, intercambios y raíces locales. Descubre Montpellier ECU, un proyecto comunitario en Base.|Persone, scambi e radici locali. Scopri Montpellier ECU, un progetto comunitario su Base.|Menschen, Austausch und lokale Wurzeln. Entdecke Montpellier ECU, ein Gemeinschaftsprojekt auf Base.|أشخاص وتبادلات وجذور محلية. اكتشف Montpellier ECU، مشروعًا مجتمعيًا على شبكة Base.|De personas, d’escambis e de rasigas localas. Descobrissètz Montpellier ECU, un projècte comunitari sus Base.
openWallet|Open Wallet|Abrir cartera|Apri il portafoglio|Wallet öffnen|افتح المحفظة|Dobrir lo portafuèlha
ecosystem|One ecosystem. Connected tools.|Un ecosistema. Herramientas conectadas.|Un ecosistema. Strumenti collegati.|Ein Ökosystem. Verbundene Werkzeuge.|منظومة واحدة وأدوات مترابطة.|Un ecosistèma. D’aisinas ligadas.
walletDescription|Connect a wallet or view a public address. Check MTP and ETH balances on Base and share your receiving QR code. This version does not sign transfers.|Conecta una cartera o consulta una dirección pública. Revisa los saldos MTP y ETH en Base y comparte tu QR. Esta versión no firma transferencias.|Collega un portafoglio o consulta un indirizzo pubblico. Controlla i saldi MTP ed ETH su Base e condividi il QR. Questa versione non firma trasferimenti.|Wallet verbinden oder öffentliche Adresse ansehen. MTP- und ETH-Guthaben auf Base prüfen und Empfangs-QR teilen. Diese Version signiert keine Transfers.|اربط محفظة أو استعرض عنوانًا عامًا. تحقق من رصيد MTP وETH على Base وشارك رمز الاستلام. هذه النسخة لا توقّع تحويلات.|Connectatz un portafuèlha o consultatz una adreça publica. Verificatz los saldes MTP e ETH sus Base e partejatz lo còdi QR. Aquesta version signa pas de transferiments.
liveDescription|Explore pools, indicative prices and dated market history. Public sources can be delayed or unavailable. A pool price is not a guaranteed execution price.|Consulta pools, precios indicativos e historial fechado. Las fuentes públicas pueden tener retrasos o fallar. El precio de una pool no garantiza el precio de ejecución.|Consulta pool, prezzi indicativi e storico datato. Le fonti pubbliche possono essere in ritardo o indisponibili. Il prezzo di una pool non garantisce il prezzo di esecuzione.|Pools, indikative Preise und datierte Kursdaten ansehen. Öffentliche Quellen können verzögert oder nicht verfügbar sein. Ein Poolpreis garantiert keinen Ausführungspreis.|استعرض مجمعات السيولة والأسعار الاسترشادية والسجل المؤرخ. قد تتأخر المصادر العامة أو تتعطل. سعر المجمع لا يضمن سعر التنفيذ.|Consultatz las pools, los prèses indicatius e l’istoric datat. Las fonts publicas pòdon èsser retardadas o indisponiblas. Lo prètz d’una pool garantís pas lo prètz d’execucion.
exchangeDescription|Objects, services and skills. Prepare a draft on this device, copy it and share it yourself. No automatic publication, orders or payments.|Objetos, servicios y conocimientos. Prepara un borrador en este dispositivo, cópialo y compártelo. Sin publicación, pedidos ni pagos automáticos.|Oggetti, servizi e competenze. Prepara una bozza su questo dispositivo, copiala e condividila. Nessuna pubblicazione, ordine o pagamento automatico.|Gegenstände, Dienste und Fähigkeiten. Entwurf auf diesem Gerät erstellen, kopieren und selbst teilen. Keine automatische Veröffentlichung, Bestellung oder Zahlung.|أغراض وخدمات ومهارات. جهّز مسودة على هذا الجهاز وانسخها وشاركها بنفسك. لا نشر أو طلبات أو مدفوعات تلقائية.|D’objèctes, de servicis e de competéncias. Preparatz un borrolhon sus aqueste aparelh, copiatz-lo e partejatz-lo. Cap de publicacion, comanda o pagament automatic.
explore|Explore|Explorar|Esplora|Entdecken|استكشف|Explorar
visionTitle|Value starts with what we share.|El valor empieza en lo que compartimos.|Il valore inizia da ciò che condividiamo.|Wert beginnt mit dem, was wir teilen.|تبدأ القيمة بما نتشاركه.|La valor comença amb çò que partejam.
vision|MTP brings together an Occitan identity, a token on Base and tools for a community under construction. Useful objects, time and skills are at the heart of the project, not promises of financial returns.|MTP reúne identidad occitana, un token en Base y herramientas para una comunidad en construcción. Los objetos útiles, el tiempo y las habilidades están en el centro, no las promesas de rentabilidad.|MTP unisce identità occitana, un token su Base e strumenti per una comunità in costruzione. Al centro ci sono oggetti utili, tempo e competenze, non promesse di rendimento.|MTP verbindet okzitanische Identität, einen Token auf Base und Werkzeuge für eine wachsende Gemeinschaft. Im Mittelpunkt stehen nützliche Dinge, Zeit und Fähigkeiten, keine Renditeversprechen.|يجمع MTP هوية أوكسيتانية ورمزًا على Base وأدوات لمجتمع قيد البناء. تركز الفكرة على الأشياء النافعة والوقت والمهارات، لا على وعود العائد المالي.|MTP liga una identitat occitana, un token sus Base e d’aisinas per una comunautat en construccion. Los objèctes utils, lo temps e las competéncias son al còr del projècte, pas las promessas de rendiment.
argent|Argent 0 means ingenuity: reuse what exists, keep infrastructure light and avoid recurring costs without compromising quality or security. Blockchain transactions may still require gas.|Argent 0 significa ingenio: reutilizar lo existente, mantener una infraestructura ligera y evitar costes recurrentes sin sacrificar calidad ni seguridad. Las transacciones blockchain pueden requerir gas.|Argent 0 significa ingegno: riutilizzare ciò che esiste, mantenere un’infrastruttura leggera ed evitare costi ricorrenti senza sacrificare qualità o sicurezza. Le transazioni blockchain possono richiedere gas.|Argent 0 steht für Einfallsreichtum: Vorhandenes nutzen, die Infrastruktur schlank halten und laufende Kosten vermeiden, ohne Qualität oder Sicherheit zu opfern. Blockchain-Transaktionen können Gas erfordern.|تعني Argent 0 الابتكار: إعادة استخدام الموجود وتبسيط البنية وتجنب التكاليف المتكررة دون التضحية بالجودة أو الأمان. قد تتطلب معاملات البلوكشين رسوم غاز.|Argent 0 vòl dire engenh : tornar utilizar l’existent, gardar una infrastructura leugièra e evitar los còstes recurrents sens sacrificar la qualitat o la seguretat. Las transaccions blockchain pòdon demandar de gas.
monia|Monia brings MTP tools to Windows. See GitHub for published releases. Version 2.0.0 was prepared locally; its public release is not confirmed.|Monia reúne las herramientas MTP en Windows. Consulta las versiones publicadas en GitHub. La versión 2.0.0 se preparó localmente; su publicación no está confirmada.|Monia riunisce gli strumenti MTP su Windows. Consulta le versioni pubblicate su GitHub. La versione 2.0.0 è stata preparata localmente; la pubblicazione non è confermata.|Monia bringt die MTP-Werkzeuge auf Windows. Veröffentlichte Versionen stehen auf GitHub. Version 2.0.0 wurde lokal erstellt; eine öffentliche Veröffentlichung ist nicht bestätigt.|يجمع Monia أدوات MTP على Windows. راجع الإصدارات المنشورة على GitHub. أُعد الإصدار 2.0.0 محليًا ولم يُؤكد نشره العام.|Monia recampa las aisinas MTP sus Windows. Consultatz las versions publicadas sus GitHub. La version 2.0.0 foguèt preparada localament ; sa publicacion es pas confirmada.
releases|Published releases|Versiones publicadas|Versioni pubblicate|Veröffentlichte Versionen|الإصدارات المنشورة|Versions publicadas
contract|Official contract · Base|Contrato oficial · Base|Contratto ufficiale · Base|Offizieller Vertrag · Base|العقد الرسمي · Base|Contracte oficial · Base
copyContract|Copy contract|Copiar contrato|Copia contratto|Vertragsadresse kopieren|نسخ العقد|Copiar lo contracte
verify|Verify on BaseScan|Verificar en BaseScan|Verifica su BaseScan|Auf BaseScan prüfen|تحقق على BaseScan|Verificar sus BaseScan
risk|MTP makes no promise of returns. Very low liquidity can prevent an exchange or cause a large price difference. Check sources and dates before interpreting a price.|MTP no promete rentabilidad. Una liquidez muy baja puede impedir un intercambio o provocar grandes diferencias de precio. Comprueba las fuentes y fechas.|MTP non promette rendimenti. Una liquidità molto bassa può impedire uno scambio o causare forti differenze di prezzo. Controlla fonti e date.|MTP verspricht keine Rendite. Sehr geringe Liquidität kann einen Tausch verhindern oder große Preisabweichungen verursachen. Quellen und Daten prüfen.|لا يقدم MTP وعودًا بالعائد. قد تمنع السيولة المنخفضة جدًا التبادل أو تسبب فرقًا كبيرًا في السعر. تحقق من المصادر والتواريخ.|MTP promet pas cap de rendiment. Una liquiditat fòrça febla pòt empachar un escambi o provocar un grand escart de prètz. Verificatz las fonts e las datas.
walletTitle|Your MTP. Your control.|Tu MTP. Bajo tu control.|Il tuo MTP. Sotto il tuo controllo.|Dein MTP. Deine Kontrolle.|MTP الخاص بك. تحت سيطرتك.|Vòstre MTP. Vòstre contraròtle.
balance|Your balance|Tu saldo|Il tuo saldo|Dein Guthaben|رصيدك|Vòstre salde
disconnected|Not connected|Sin conexión|Non connesso|Nicht verbunden|غير متصل|Pas connectat
connect|Connect a wallet|Conectar cartera|Collega portafoglio|Wallet verbinden|ربط محفظة|Connectar un portafuèlha
refresh|Refresh|Actualizar|Aggiorna|Aktualisieren|تحديث|Actualizar
noWallet|No wallet connected.|Ninguna cartera conectada.|Nessun portafoglio collegato.|Keine Wallet verbunden.|لا توجد محفظة متصلة.|Cap de portafuèlha connectat.
watch|Or view a public address|O consulta una dirección pública|Oppure consulta un indirizzo pubblico|Oder öffentliche Adresse ansehen|أو استعرض عنوانًا عامًا|O consultar una adreça publica
readOnly|Read only: no signature or transaction.|Solo lectura: sin firmas ni transacciones.|Sola lettura: nessuna firma o transazione.|Nur lesen: keine Signatur oder Transaktion.|قراءة فقط: بلا توقيع أو معاملة.|Lectura sola : cap de signatura ni transaccion.
viewAddress|View this address|Consultar dirección|Consulta indirizzo|Adresse ansehen|استعراض العنوان|Consultar aquesta adreça
active|Active address|Dirección activa|Indirizzo attivo|Aktive Adresse|العنوان النشط|Adreça activa
copyAddress|Copy address|Copiar dirección|Copia indirizzo|Adresse kopieren|نسخ العنوان|Copiar l’adreça
explorer|Explorer|Explorador|Explorer|Explorer|المستكشف|Explorador
clear|Clear local session|Borrar sesión local|Cancella sessione locale|Lokale Sitzung löschen|مسح الجلسة المحلية|Escafar la session locala
receive|Receive MTP|Recibir MTP|Ricevi MTP|MTP empfangen|استلام MTP|Recebre MTP
receiveText|Share your public address to receive MTP on Base. The QR contains only the address: the sender must use Base and the official MTP contract.|Comparte tu dirección pública para recibir MTP en Base. El QR solo contiene la dirección: utiliza Base y el contrato oficial MTP.|Condividi l’indirizzo pubblico per ricevere MTP su Base. Il QR contiene solo l’indirizzo: il mittente deve usare Base e il contratto ufficiale MTP.|Teile deine öffentliche Adresse für MTP auf Base. Der QR enthält nur die Adresse: Der Absender muss Base und den offiziellen MTP-Vertrag nutzen.|شارك عنوانك العام لاستلام MTP على Base. يتضمن الرمز العنوان فقط: يجب استخدام Base وعقد MTP الرسمي.|Partejàtz vòstra adreça publica per recebre MTP sus Base. Lo QR conten pas que l’adreça : l’expeditor deu utilizar Base e lo contracte MTP oficial.
qrEmpty|Your QR appears after connecting or viewing an address.|El QR aparece al conectar o consultar una dirección.|Il QR appare dopo la connessione o la consultazione di un indirizzo.|Der QR erscheint nach dem Verbinden oder Anzeigen einer Adresse.|يظهر الرمز بعد الربط أو استعراض عنوان.|Lo QR apareis aprèp connexion o consultacion d’una adreça.
qrLabel|Public address QR code|QR de dirección pública|QR dell’indirizzo pubblico|QR der öffentlichen Adresse|رمز العنوان العام|Còdi QR de l’adreça publica
liveTitle|See the activity. Understand the data.|Observa la actividad. Entiende los datos.|Osserva l’attività. Comprendi i dati.|Aktivität sehen. Daten verstehen.|تابع النشاط وافهم البيانات.|Veire l’activitat. Comprendre las donadas.
loading|Loading public sources…|Cargando fuentes públicas…|Caricamento fonti pubbliche…|Öffentliche Quellen werden geladen…|جارٍ تحميل المصادر العامة…|Cargament de las fonts publicas…
poolCount|Pools returned|Pools encontradas|Pool restituite|Gefundene Pools|المجمعات المعروضة|Pools retornadas
availableSources|From available sources|De las fuentes disponibles|Dalle fonti disponibili|Aus verfügbaren Quellen|من المصادر المتاحة|De las fonts disponiblas
liquidityTotal|Total liquidity|Liquidez total|Liquidità totale|Gesamtliquidität|إجمالي السيولة|Liquiditat totala
shownPools|USD · displayed pools|USD · pools mostradas|USD · pool mostrate|USD · angezeigte Pools|USD · المجمعات المعروضة|USD · pools afichadas
volume24|24 h volume|Volumen 24 h|Volume 24 h|24-h-Volumen|حجم 24 ساعة|Volum 24 h
pool|Pool / platform|Pool / plataforma|Pool / piattaforma|Pool / Plattform|المجمع / المنصة|Pool / plataforma
price|Indicative MTP price|Precio indicativo MTP|Prezzo indicativo MTP|Indikativer MTP-Preis|سعر MTP الاسترشادي|Prètz indicatiu MTP
liquidity|Liquidity|Liquidez|Liquidità|Liquidität|السيولة|Liquiditat
source|Source|Fuente|Fonte|Quelle|المصدر|Font
context|A number needs context.|Un número necesita contexto.|Un numero richiede contesto.|Zahlen brauchen Kontext.|الأرقام تحتاج إلى سياق.|Un nombre demanda un contèxte.
contextText|Missing from an aggregator does not mean the token has disappeared. Missing values are shown as —, never replaced with invented estimates. Totals cover only displayed pools.|No aparecer en un agregador no significa que el token haya desaparecido. Los valores ausentes se muestran como —, sin estimaciones inventadas. Los totales solo incluyen las pools mostradas.|L’assenza da un aggregatore non significa che il token sia scomparso. I valori mancanti sono indicati con —, senza stime inventate. I totali riguardano solo le pool mostrate.|Fehlende Daten bei einem Aggregator bedeuten nicht, dass der Token verschwunden ist. Fehlende Werte erscheinen als —, ohne erfundene Schätzungen. Summen gelten nur für angezeigte Pools.|غياب الرمز عن مجمّع بيانات لا يعني اختفاءه. تظهر القيم المفقودة بعلامة — دون تقديرات مختلقة. تشمل المجاميع المجمعات المعروضة فقط.|L’abséncia dins un agregador significa pas que lo token a desaparegut. Las valors mancantas son afichadas amb —, sens estimacions inventadas. Los totals concernisson sonque las pools afichadas.
exchangeTitle|Less unused. More possibilities.|Menos sin usar. Más posibilidades.|Meno inutilizzato. Più possibilità.|Weniger ungenutzt. Mehr Möglichkeiten.|أقل هدرًا وأكثر إمكانات.|Mens d’inutilizat. Mai de possibilitats.
draftTitle|Your next listing.|Tu próximo anuncio.|Il tuo prossimo annuncio.|Dein nächstes Angebot.|إعلانك القادم.|Vòstre anonci venent.
localDraft|Local draft · not published|Borrador local · no publicado|Bozza locale · non pubblicata|Lokaler Entwurf · nicht veröffentlicht|مسودة محلية · غير منشورة|Borrolhon local · pas publicat
title|Title|Título|Titolo|Titel|العنوان|Títol
category|Category|Categoría|Categoria|Kategorie|الفئة|Categoria
object|Object|Objeto|Oggetto|Gegenstand|غرض|Objècte
service|Service|Servicio|Servizio|Dienstleistung|خدمة|Servici
skill|Skill|Habilidad|Competenza|Fähigkeit|مهارة|Competéncia
gift|Donation|Donación|Dono|Spende|تبرع|Don
description|Description|Descripción|Descrizione|Beschreibung|الوصف|Descripcion
amount|Amount in MTP (optional)|Importe en MTP (opcional)|Importo in MTP (facoltativo)|Betrag in MTP (optional)|المبلغ بـ MTP (اختياري)|Montant en MTP (facultatiu)
negotiable|To be agreed|A convenir|Da concordare|Nach Vereinbarung|بالاتفاق|De convéner
save|Save draft|Guardar borrador|Salva bozza|Entwurf speichern|حفظ المسودة|Enregistrar lo borrolhon
yourDrafts|Your drafts.|Tus borradores.|Le tue bozze.|Deine Entwürfe.|مسوداتك.|Vòstres borrolhons.
deviceOnly|Stored only on this device|Solo en este dispositivo|Solo su questo dispositivo|Nur auf diesem Gerät gespeichert|محفوظة على هذا الجهاز فقط|Enregistrats sonque sus aqueste aparelh
privacyTitle|Your data. Clearly explained.|Tus datos. Con claridad.|I tuoi dati. Con chiarezza.|Deine Daten. Klar erklärt.|بياناتك بوضوح.|Vòstras donadas. Clarament.
storageTitle|Local storage|Almacenamiento local|Archiviazione locale|Lokaler Speicher|التخزين المحلي|Estocatge local
storageText|The last viewed address and listing drafts are stored in your browser. Clear the Wallet session, delete individual drafts or clear the website data in your browser to remove them.|La última dirección y los borradores se guardan en el navegador. Borra la sesión del Wallet, elimina los borradores o borra los datos del sitio para retirarlos.|L’ultimo indirizzo e le bozze sono salvati nel browser. Cancella la sessione Wallet, elimina le bozze o cancella i dati del sito per rimuoverli.|Letzte Adresse und Entwürfe werden im Browser gespeichert. Wallet-Sitzung leeren, Entwürfe einzeln löschen oder Website-Daten im Browser entfernen.|يُحفظ آخر عنوان والمسودات في المتصفح. امسح جلسة المحفظة أو احذف المسودات أو بيانات الموقع لإزالتها.|La darrièra adreça e los borrolhons son gardats dins lo navegador. Escafatz la session Wallet, los borrolhons o las donadas del site per los suprimir.
externalTitle|External services|Servicios externos|Servizi esterni|Externe Dienste|الخدمات الخارجية|Servicis extèrnes
externalText|Base RPC receives the public address when balances are requested. GeckoTerminal, DexScreener and Blockscout supply market data and transfers. These services and Cloudflare receive technical request data, including IP addresses. No advertising or analytics script is included.|El RPC de Base recibe la dirección pública al consultar saldos. GeckoTerminal, DexScreener y Blockscout aportan datos y transferencias. Estos servicios y Cloudflare reciben datos técnicos, incluida la IP. No hay scripts de publicidad ni analítica.|Il RPC Base riceve l’indirizzo pubblico per i saldi. GeckoTerminal, DexScreener e Blockscout forniscono dati e trasferimenti. Questi servizi e Cloudflare ricevono dati tecnici, incluso l’IP. Nessuno script pubblicitario o di analisi.|Der Base-RPC erhält die öffentliche Adresse für Guthabenabfragen. GeckoTerminal, DexScreener und Blockscout liefern Markt- und Transferdaten. Diese Dienste und Cloudflare erhalten technische Daten einschließlich IP-Adressen. Keine Werbe- oder Analyseskripte.|يتلقى RPC الخاص بـ Base العنوان العام عند طلب الرصيد. توفر GeckoTerminal وDexScreener وBlockscout بيانات السوق والتحويلات. تتلقى هذه الخدمات وCloudflare بيانات تقنية منها عنوان IP. لا توجد برامج إعلانات أو تحليلات.|Lo RPC Base recep l’adreça publica per consultar los saldes. GeckoTerminal, DexScreener e Blockscout provesisson las donadas e los transferiments. Aquestes servicis e Cloudflare recebon de donadas tecnicas, dont l’IP. Cap de programa publicitari o de mesura d’audiéncia.
walletPrivacy|You choose which accounts to share with the site. No recovery phrase, private key or signing secret is requested. Reading a balance does not create a transaction.|Tú eliges qué cuentas compartir. No se solicita frase de recuperación, clave privada ni secreto de firma. Consultar un saldo no crea una transacción.|Scegli quali conti condividere. Non vengono richiesti frase di recupero, chiave privata o segreti di firma. Leggere un saldo non crea una transazione.|Du entscheidest, welche Konten du teilst. Keine Wiederherstellungsphrase, privaten Schlüssel oder Signaturgeheimnisse werden angefordert. Eine Guthabenabfrage erzeugt keine Transaktion.|تختار الحسابات التي تشاركها. لا تُطلب عبارة استرداد أو مفتاح خاص أو سر توقيع. قراءة الرصيد لا تنشئ معاملة.|Causissètz los comptes de partejar. Cap de frasa de recuperacion, clau privada o secret de signatura es demandat. La lectura d’un salde crea pas de transaccion.
docsTitle|Facts. Open evidence.|Hechos. Pruebas abiertas.|Fatti. Prove aperte.|Fakten. Offene Nachweise.|حقائق وأدلة مفتوحة.|De faches. De pròvas dobèrtas.
proofTitle|The official contract, reproduced exactly.|El contrato oficial, reproducido exactamente.|Il contratto ufficiale, riprodotto esattamente.|Der offizielle Vertrag, exakt reproduziert.|العقد الرسمي، مُعاد إنتاجه بدقة.|Lo contracte oficial, reprodusit exactament.
proofText|Checked on 22 September 2026: the full 1,764-byte runtime and creation code match the independent compilation, including metadata. Solidity 0.8.30, optimizer 200 runs, Cancun EVM. 21 million MTP were created at deployment, with 18 decimals.|Verificado el 22 de septiembre de 2026: los 1764 bytes del código ejecutado y el código de creación coinciden con la compilación independiente, incluidos los metadatos. Solidity 0.8.30, optimización 200 runs, EVM Cancun. Se crearon 21 millones de MTP con 18 decimales.|Verificato il 22 settembre 2026: i 1764 byte del codice eseguito e il codice di creazione coincidono con la compilazione indipendente, metadati inclusi. Solidity 0.8.30, ottimizzazione 200 runs, EVM Cancun. Creati 21 milioni di MTP con 18 decimali.|Am 22. September 2026 geprüft: Die vollständigen 1.764 Runtime-Bytes und der Erstellungscode stimmen einschließlich Metadaten mit der unabhängigen Kompilierung überein. Solidity 0.8.30, Optimierer 200 Runs, Cancun-EVM. Bei Erstellung entstanden 21 Millionen MTP mit 18 Dezimalstellen.|تم التحقق في 22 سبتمبر 2026: يطابق كود التشغيل الكامل البالغ 1764 بايت وكود الإنشاء التجميع المستقل، بما فيه البيانات الوصفية. Solidity 0.8.30 وتحسين 200 دورة وEVM Cancun. أُنشئ 21 مليون MTP عند النشر بـ18 منزلة عشرية.|Verificat lo 22 de setembre de 2026 : los 1 764 octets del còdi executat e lo còdi de creacion correspondon a la compilacion independenta, metadonadas inclusas. Solidity 0.8.30, optimizacion 200 runs, EVM Cancun. 21 milions de MTP creats al desplegament, amb 18 decimalas.
proofLimits|This code has no externally accessible additional mint, Ownable administration, transfer tax, blacklist, pause or proxy. This is a code correspondence check, not a comprehensive security audit or a guarantee of liquidity or returns. Historical references to 10.5 million initial tokens concern an earlier generation.|Este código no tiene mint adicional accesible, administración Ownable, impuesto de transferencia, blacklist, pausa ni proxy. La verificación no es una auditoría de seguridad exhaustiva ni garantiza liquidez o rentabilidad. Los 10,5 millones iniciales históricos corresponden a una generación anterior.|Questo codice non ha mint aggiuntivo accessibile, amministrazione Ownable, tassa sui trasferimenti, blacklist, pausa o proxy. La verifica non è un audit di sicurezza completo né una garanzia di liquidità o rendimento. I 10,5 milioni iniziali storici riguardano una generazione precedente.|Dieser Code hat kein extern zugängliches zusätzliches Minting, keine Ownable-Verwaltung, Transfersteuer, Blacklist, Pause oder Proxy. Die Prüfung ist kein umfassendes Sicherheitsaudit und garantiert weder Liquidität noch Rendite. Historische 10,5 Millionen Anfangstoken betreffen eine frühere Generation.|لا يحتوي هذا الكود على سك إضافي متاح خارجيًا أو إدارة Ownable أو ضريبة تحويل أو قائمة حظر أو إيقاف أو وكيل. هذا تحقق من تطابق الكود وليس تدقيقًا أمنيًا شاملًا أو ضمانًا للسيولة والعائد. تشير 10.5 ملايين الأولية تاريخيًا إلى جيل سابق.|Aqueste còdi a pas de mint suplementari accessible, administracion Ownable, taxa de transferiment, lista de blocatge, pausa o proxy. La verificacion es pas un audit de seguretat complet ni una garantia de liquiditat o rendiment. Los 10,5 milions inicials istorics concernisson una generacion anteriora.
download|Download evidence (French report)|Descargar pruebas (informe francés)|Scarica prove (rapporto francese)|Nachweise herunterladen (Bericht auf Französisch)|تنزيل الأدلة (تقرير بالفرنسية)|Telecargar las pròvas (rapòrt en francés)
creation|Creation transaction|Transacción de creación|Transazione di creazione|Erstellungstransaktion|معاملة الإنشاء|Transaccion de creacion
current|What works today|Qué funciona hoy|Cosa funziona oggi|Was heute funktioniert|ما يعمل اليوم|Çò que fonciona uèi
pilot|A proposal to test: a few volunteers offering useful services, with real demand checked before spending. This is not a launched service and does not promise a higher token price.|Propuesta a probar: voluntarios que ofrezcan servicios útiles, comprobando la demanda antes de gastar. No es un servicio lanzado ni promete subir el precio del token.|Proposta da testare: volontari con servizi utili, verificando la domanda prima di spendere. Non è un servizio avviato e non promette un aumento del prezzo.|Testvorschlag: Freiwillige bieten nützliche Dienste an; Nachfrage wird vor Ausgaben geprüft. Kein bereits gestarteter Dienst und kein Versprechen steigender Tokenpreise.|اقتراح للاختبار: متطوعون يقدمون خدمات نافعة، مع التحقق من الطلب قبل الإنفاق. ليست خدمة أُطلقت ولا وعدًا بارتفاع السعر.|Proposicion de testar : de volontaris prepausan de servicis utils, amb verificacion de la demanda abans de despensar. Es pas un servici lançat ni una promessa de pujada del prètz.
language|Language|Idioma|Lingua|Sprache|اللغة|Lenga
translationNote|Occitan version: linguistic review welcome.|Versión occitana: se agradece revisión lingüística.|Versione occitana: revisione linguistica benvenuta.|Okzitanische Version: sprachliche Prüfung willkommen.|النسخة الأوكسيتانية: نرحب بالمراجعة اللغوية.|Version occitana : una relectura lingüistica es benvenguda.
`;
const languages=['en','es','it','de','ar','oc'];const data=Object.fromEntries(languages.map(l=>[l,{}]));for(const line of rows.trim().split('\n')){const [key,...values]=line.split('|');if(values.length!==6)throw Error('Translation row '+key);languages.forEach((l,i)=>data[l][key]=values[i]);}module.exports={languages,data};
