const text={
fr:['La marketplace se prépare.','Biens','Services','Objets, créations et biens autorisés par la charte.','Compétences et prestations autorisées par la charte.','Compte, annonce et commande : validation manuelle avant paiement.','Drogues, prostitution, prestations sexuelles, escroqueries et biens illicites interdits.','Commission : 0,20 € ajoutés au prix acheteur, convertis en MTP. Frais réseau éventuels séparés.','Comptes et paiements non ouverts. Les annonces restent des brouillons locaux.','Lire la charte','Préparer une annonce','Charte'],
en:['The marketplace is being prepared.','Goods','Services','Objects, creations and goods permitted by the charter.','Skills and services permitted by the charter.','Account, listing and order: manual approval before payment.','Drugs, prostitution, sexual services, scams and illegal goods are prohibited.','Fee: €0.20 added to the buyer’s price, converted to MTP. Any network fees are separate.','Accounts and payments are not open. Listings remain local drafts.','Read the charter (French)','Prepare a listing','Charter (FR)'],
es:['La marketplace está en preparación.','Bienes','Servicios','Objetos, creaciones y bienes permitidos por la carta.','Habilidades y servicios permitidos por la carta.','Cuenta, anuncio y pedido: aprobación manual antes del pago.','Se prohíben drogas, prostitución, servicios sexuales, estafas y bienes ilegales.','Comisión: 0,20 € añadidos al precio del comprador, convertidos a MTP. Gastos de red aparte.','Las cuentas y los pagos aún no están abiertos. Los anuncios siguen siendo borradores locales.','Leer la carta (francés)','Preparar un anuncio','Carta (FR)'],
it:['Il marketplace è in preparazione.','Beni','Servizi','Oggetti, creazioni e beni consentiti dalla carta.','Competenze e servizi consentiti dalla carta.','Account, annuncio e ordine: approvazione manuale prima del pagamento.','Droghe, prostituzione, servizi sessuali, truffe e beni illegali sono vietati.','Commissione: 0,20 € aggiunti al prezzo dell’acquirente, convertiti in MTP. Eventuali costi di rete separati.','Account e pagamenti non sono ancora aperti. Gli annunci restano bozze locali.','Leggi la carta (francese)','Prepara un annuncio','Carta (FR)'],
de:['Der Marktplatz wird vorbereitet.','Waren','Dienstleistungen','Gegenstände, Werke und Waren, die nach den Regeln zulässig sind.','Fähigkeiten und Leistungen, die nach den Regeln zulässig sind.','Konto, Anzeige und Bestellung: manuelle Freigabe vor der Zahlung.','Drogen, Prostitution, sexuelle Dienstleistungen, Betrug und illegale Waren sind verboten.','Gebühr: 0,20 € zusätzlich zum Käuferpreis, umgerechnet in MTP. Etwaige Netzwerkgebühren separat.','Konten und Zahlungen sind noch nicht freigeschaltet. Anzeigen bleiben lokale Entwürfe.','Regeln lesen (Französisch)','Anzeige vorbereiten','Regeln (FR)'],
ar:['السوق قيد التحضير.','السلع','الخدمات','الأغراض والإبداعات والسلع التي يسمح بها الميثاق.','المهارات والخدمات التي يسمح بها الميثاق.','الحساب والإعلان والطلب: موافقة يدوية قبل الدفع.','تُحظر المخدرات والدعارة والخدمات الجنسية والاحتيال والسلع غير القانونية.','تضاف عمولة 0.20 يورو إلى سعر المشتري وتحول إلى MTP. رسوم الشبكة المحتملة منفصلة.','الحسابات والمدفوعات غير متاحة بعد. تبقى الإعلانات مسودات محلية.','قراءة الميثاق بالفرنسية','إعداد إعلان','الميثاق (FR)'],
oc:['La plaça de mercat se prepara.','Bens','Servicis','Objèctes, creacions e bens autorizats per la carta.','Competéncias e servicis autorizats per la carta.','Compte, anóncia e comanda : validacion manuala abans lo pagament.','Drògas, prostitucion, servicis sexuals, escroquerias e bens illegals enebits.','Comission : 0,20 € ajustats al prètz de l’acrompaire, convertits en MTP. Fraisses de ret eventuals separats.','Comptes e pagaments pas encara dobèrts. Las anóncias demòran d’esbòs locals.','Legir la carta (francés)','Preparar una anóncia','Carta (FR)']
};
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function inline(s){return esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code style="overflow-wrap:anywhere">$1</code>')}
function markdown(s){let list=false;return s.split(/\r?\n/).map(line=>{let out='';const item=/^(?:- |\d+\. )(.+)$/.exec(line);if(list&&!item){out+='</ul>';list=false}if(item){if(!list){out+='<ul>';list=true}return out+'<li>'+inline(item[1])+'</li>'}if(!line.trim())return out;const heading=/^(#{1,3}) (.+)$/.exec(line);return out+(heading?`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`:'<p>'+inline(line)+'</p>')}).join('')+(list?'</ul>':'')}
module.exports=function({fs,path,root,shell,base}){
 const charter=fs.readFileSync(path.join(__dirname,'CHARTE-MARKETPLACE-MTP.md'),'utf8');
 const dir=path.join(root,'charte');fs.mkdirSync(dir,{recursive:true});
 fs.writeFileSync(path.join(dir,'index.html'),shell('/charte/',{title:'Charte de la marketplace — Montpellier ECU',description:'Biens et services, validation manuelle et règles de la future marketplace MTP.',content:'<div class="wrap"><article class="panel" style="margin:50px 0;line-height:1.8">'+markdown(charter)+'</article></div>'}));
 const routes=['','wallet','live','echanges','documentation','confidentialite'];
 for(const [lang,t] of Object.entries(text)){for(const route of routes){const file=path.join(root,lang==='fr'?'':lang,route,'index.html');let html=fs.readFileSync(file,'utf8');html=html.replace('<div class="footer-bottom">',`<p><a class="textlink" href="/charte/" hreflang="fr">${t[11]} ↗</a></p><div class="footer-bottom">`);
 if(route==='echanges'){const section=`<section class="section" id="marketplace"><h2>${t[0]}</h2><p class="notice">${t[8]}</p><div class="workspace"><article class="card"><h3>${t[1]}</h3><p>${t[3]}</p><a class="textlink" href="#listing-form">${t[10]} →</a></article><article class="card"><h3>${t[2]}</h3><p>${t[4]}</p><a class="textlink" href="#listing-form">${t[10]} →</a></article></div><p><strong>${t[5]}</strong></p><p>${t[6]}</p><p>${t[7]}</p><a class="button secondary" href="/charte/" hreflang="fr">${t[9]} ↗</a></section>`;html=html.replace('<div class="workspace">',section+'<div class="workspace">')}
 fs.writeFileSync(file,html)}}
 const sitemap=path.join(root,'sitemap.xml');fs.writeFileSync(sitemap,fs.readFileSync(sitemap,'utf8').replace('</urlset>','<url><loc>'+base+'/charte/</loc></url></urlset>'));
};
