// Original MTP choreography using browser APIs; no third-party animation code.
export function initPremiumMotion(){
 const reduce=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover: hover) and (pointer: fine)'),root=document.documentElement;
 const words={fr:['Animations : actives','Animations : désactivées'],en:['Motion: on','Motion: off'],es:['Animaciones: activas','Animaciones: desactivadas'],it:['Animazioni: attive','Animazioni: disattivate'],de:['Animationen: an','Animationen: aus'],ar:['الحركة: مفعلة','الحركة: متوقفة'],oc:['Animacions : activas','Animacions : desactivadas']},labels=words[root.lang]||words.fr;
 let userOff=false;try{userOff=sessionStorage.getItem('mtp.motion.off')==='1'}catch{}
 const control=document.createElement('button');control.type='button';control.className='motion-control';document.querySelector('.footer .wrap')?.append(control);
 const running=new Set();let enabled=false,frame=0;const scene=document.querySelector('.cinema-art'),screen=document.querySelector('.cinema-screen');
 if(scene){const dust=document.createElement('div');dust.className='gold-dust';dust.setAttribute('aria-hidden','true');for(let i=0;i<18;i++){const p=document.createElement('i');p.style.cssText=`--x:${(i*37+11)%100}%;--y:${(i*53+7)%100}%;--delay:${-(i%7)}s;--duration:${7+i%5}s`;dust.append(p)}scene.prepend(dust);const halo=document.createElement('div');halo.className='orbital-light';halo.setAttribute('aria-hidden','true');scene.prepend(halo)}
 const animate=(el,frames,options)=>{if(!enabled||!el.animate)return;const a=el.animate(frames,options);running.add(a);a.finished.catch(()=>{}).finally(()=>running.delete(a));};
 function reset(){if(frame)cancelAnimationFrame(frame);frame=0;if(screen){screen.style.removeProperty('--tilt-x');screen.style.removeProperty('--tilt-y');screen.style.removeProperty('--shine-x')}}
 function sync(){enabled=!userOff&&!reduce.matches;root.classList.toggle('motion-on',enabled);root.classList.toggle('motion-background',document.hidden);control.textContent=labels[enabled?0:1];control.setAttribute('aria-pressed',String(enabled));if(!enabled){for(const a of running)a.cancel();reset();const intro=document.querySelector('.screen-intro');if(intro)intro.hidden=true}else for(const a of running)document.hidden?a.pause():a.play()}
 control.onclick=()=>{userOff=enabled;try{sessionStorage.setItem('mtp.motion.off',userOff?'1':'0')}catch{}sync()};reduce.addEventListener('change',sync);document.addEventListener('visibilitychange',sync);sync();
 const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const el=entry.target;observer.unobserve(el);animate(el,[{opacity:.45,transform:'translateY(24px)'},{opacity:1,transform:'translateY(0)'}],{duration:850,easing:'cubic-bezier(.16,1,.3,1)'})}},{threshold:.12});document.querySelectorAll('.section-head,.story,.page-hero,#ecosysteme .card,.stats,.gold-chart').forEach(el=>observer.observe(el));
 if(scene){const visible=new IntersectionObserver(entries=>{scene.classList.toggle('scene-visible',entries[0].isIntersecting)},{threshold:.05});visible.observe(scene);scene.addEventListener('pointermove',e=>{if(!enabled||!fine.matches||document.hidden||frame)return;const rect=scene.getBoundingClientRect(),x=Math.max(-.5,Math.min(.5,(e.clientX-rect.left)/rect.width-.5)),y=Math.max(-.5,Math.min(.5,(e.clientY-rect.top)/rect.height-.5));frame=requestAnimationFrame(()=>{frame=0;screen.style.setProperty('--tilt-y',x*9+'deg');screen.style.setProperty('--tilt-x',-y*6+'deg');screen.style.setProperty('--shine-x',(x+.5)*100+'%')})},{passive:true});scene.addEventListener('pointerleave',reset);fine.addEventListener('change',reset)}
 const delay=document.querySelector('.screen-intro:not([hidden])')?1750:40;setTimeout(()=>{document.querySelectorAll('.cinema-copy>*').forEach((el,i)=>animate(el,[{opacity:.4,transform:'translateY(20px)'},{opacity:1,transform:'translateY(0)'}],{duration:1050,delay:i*85,easing:'cubic-bezier(.16,1,.3,1)'}));if(scene)animate(scene,[{opacity:.25,transform:'translateY(30px) scale(.96)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:1400,easing:'cubic-bezier(.16,1,.3,1)'})},delay);
}
