const copy={
fr:['UN ÉCRAN. UNE HISTOIRE. UN MONDE.','Tout part','d’un écran.','La suite s’écrit ensemble.','Des histoires à raconter. Des créations à partager. Des échanges à inventer. Bienvenue dans l’univers Montpellier ECU.','Entrer dans l’univers','Ouvrir le Wallet','NÉ EN OCCITANIE','OUVERT SUR LE MONDE','LE PROJET / 01'],
en:['A SCREEN. A STORY. A WORLD.','It starts','with a screen.','We write what comes next together.','Stories to tell. Creations to share. Exchanges to imagine. Welcome to the world of Montpellier ECU.','Explore the universe','Open the Wallet','BORN IN OCCITANIA','OPEN TO THE WORLD','THE PROJECT / 01'],
es:['UNA PANTALLA. UNA HISTORIA. UN MUNDO.','Todo empieza','en una pantalla.','Lo que sigue lo escribimos juntos.','Historias que contar. Creaciones que compartir. Intercambios que imaginar. Bienvenido al universo Montpellier ECU.','Entrar en el universo','Abrir el Wallet','NACIDO EN OCCITANIA','ABIERTO AL MUNDO','EL PROYECTO / 01'],
it:['UNO SCHERMO. UNA STORIA. UN MONDO.','Tutto inizia','da uno schermo.','Il seguito lo scriviamo insieme.','Storie da raccontare. Creazioni da condividere. Scambi da immaginare. Benvenuti nell’universo Montpellier ECU.','Entra nell’universo','Apri il Wallet','NATO IN OCCITANIA','APERTO AL MONDO','IL PROGETTO / 01'],
de:['EIN BILDSCHIRM. EINE GESCHICHTE. EINE WELT.','Alles beginnt','mit einem Bildschirm.','Wir schreiben gemeinsam weiter.','Geschichten erzählen. Kreativität teilen. Austausch gestalten. Willkommen in der Welt von Montpellier ECU.','Die Welt entdecken','Wallet öffnen','IN OKZITANIEN GEBOREN','OFFEN FÜR DIE WELT','DAS PROJEKT / 01'],
ar:['شاشة. حكاية. عالم.','كل شيء يبدأ','من شاشة.','نكتب ما يأتي بعدها معاً.','حكايات نرويها. إبداعات نتشاركها. وتبادل نتخيله معاً. مرحباً بك في عالم مونبلييه ECU.','اكتشف العالم','افتح المحفظة','من أوكسيتانيا','منفتح على العالم','المشروع / 01'],
oc:['UN ECRAN. UNA ISTÒRIA. UN MOND.','Tot comença','amb un ecran.','La seguida s’escriu amassa.','D’istòrias de contar. De creacions de partejar. D’escambis d’inventar. Benvenguts dins l’univèrs Montpelhièr ECU.','Dintrar dins l’univèrs','Dobrir lo Wallet','NASCUT EN OCCITÀNIA','DOBÈRT SUL MOND','LO PROJÈCTE / 01']};
module.exports=function({fs,path,root}){function visit(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,e.name);if(e.isDirectory())visit(file);else if(e.name.endsWith('.html')){let html=fs.readFileSync(file,'utf8');if(!html.includes('href="/premium.css"'))html=html.replace('</head>','<link rel="stylesheet" href="/premium.css"></head>');if(html.includes('<section class="hero">')){const lang=html.match(/<html lang="([a-z]+)"/)?.[1]||'fr',t=copy[lang]||copy.fr,prefix=lang==='fr'?'':'/'+lang;const hero=`<section class="hero cinema-hero"><div class="cinema-copy"><div class="eyebrow">${t[0]}</div><h1>${t[1]}<br><em>${t[2]}</em></h1><p class="cinema-subtitle">${t[3]}</p><p class="lede">${t[4]}</p><div class="actions"><a class="button" href="${html.includes('id="ecosysteme"')?'#ecosysteme':'#vision'}">${t[5]} <span>↘</span></a><a class="textlink" href="${prefix}/wallet/">${t[6]} ↗</a></div></div><div class="cinema-art" aria-hidden="true"><div class="screen-halo"></div><div class="cinema-screen"><div class="screen-topline"><span>MONTPELLIER ECU</span><span>01 — MTP</span></div><div class="screen-surface"><img src="/assets/logo.png" alt="" width="512" height="512"><span class="screen-name">MTP</span><span class="screen-caption">MONTPELLIER ECU</span></div><div class="screen-bottomline"><span>CRÉATION · COMMUNAUTÉ</span><span>BASE / 8453</span></div></div><div class="screen-foot"></div><div class="screen-ground"></div><span class="screen-coordinate">43°36′ N &nbsp; 3°52′ E</span></div><div class="cinema-baseline"><span>${t[7]}</span><span>${t[9]}</span><span>${t[8]} &nbsp; ↓</span></div></section>`;html=html.replace(/<section class="hero">[\s\S]*?<\/section>/,hero)}fs.writeFileSync(file,html)}}}visit(root)};
